# CMake generated Testfile for 
# Source directory: C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak
# Build directory: C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/smartpeak
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ApplicationProcessor_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/ApplicationProcessor_test")
set_tests_properties(ApplicationProcessor_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(CastValue_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/CastValue_test")
set_tests_properties(CastValue_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(Filenames_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/Filenames_test")
set_tests_properties(Filenames_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(Helloworld_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/Helloworld_test")
set_tests_properties(Helloworld_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(MetaDataHandler_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/MetaDataHandler_test")
set_tests_properties(MetaDataHandler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(RawDataHandler_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/RawDataHandler_test")
set_tests_properties(RawDataHandler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(RawDataProcessor_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/RawDataProcessor_test")
set_tests_properties(RawDataProcessor_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(SampleGroupHandler_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/SampleGroupHandler_test")
set_tests_properties(SampleGroupHandler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(SampleGroupProcessor_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/SampleGroupProcessor_test")
set_tests_properties(SampleGroupProcessor_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(InjectionHandler_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/InjectionHandler_test")
set_tests_properties(InjectionHandler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(SequenceHandler_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/SequenceHandler_test")
set_tests_properties(SequenceHandler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(SequenceProcessor_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/SequenceProcessor_test")
set_tests_properties(SequenceProcessor_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(SequenceSegmentHandler_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/SequenceSegmentHandler_test")
set_tests_properties(SequenceSegmentHandler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(SequenceSegmentProcessor_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/SequenceSegmentProcessor_test")
set_tests_properties(SequenceSegmentProcessor_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(SessionHandler_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/SessionHandler_test")
set_tests_properties(SessionHandler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(Utilities_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/Utilities_test")
set_tests_properties(Utilities_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(CSVWriter_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/CSVWriter_test")
set_tests_properties(CSVWriter_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(FileReader_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/FileReader_test")
set_tests_properties(FileReader_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(SequenceParser_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/SequenceParser_test")
set_tests_properties(SequenceParser_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(InputDataValidation_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/InputDataValidation_test")
set_tests_properties(InputDataValidation_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(MRMFeatureValidator_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/MRMFeatureValidator_test")
set_tests_properties(MRMFeatureValidator_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(GuiAppender_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/GuiAppender_test")
set_tests_properties(GuiAppender_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
add_test(WindowSizesAndPositions_test "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/src/tests/class_tests/bin/WindowSizesAndPositions_test")
set_tests_properties(WindowSizesAndPositions_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;132;add_test;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/src/tests/class_tests/smartpeak/CMakeLists.txt;0;")
