version: '1.0.{build}'
image: Visual Studio 2017
force_https_clone: true
clone_depth: 1
environment:
  APPVEYOR_RDP_PASSWORD: z1x2c3V4
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  BOOST_TEST_DETECT_MEMORY_LEAK: 0
  CLCACHE_DIR: C:\projects\clcache
  CLCACHE_HARDLINK: 1
  CLCACHE_SERVER: 1

# scripts that are called at very beginning, before repo cloning
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - PATH=C:\Python37-x64;C:\Python37-x64\Scripts;C:\projects\clcache\install\bin;C:\projects\OpenMS-build\bin\Debug;C:\Qt\5.12\msvc2017_64\bin;C:\projects\deps\SDL2-2.0.9\lib\x64;%PATH%
  - set PYTHONPATH=C:\projects\clcache\install
  - cmake --version
  - pip3 --version

platform: x64
configuration: Debug

cache:
  - C:\projects\deps
  - C:\projects\OpenMS
  - C:\projects\OpenMS-build
  - C:\projects\clcache

# artifacts can only be found in the repo dir (i.e. C:\projects\SmartPeak2) or subdirs
artifacts:
  - path: build\bin\Debug
    name: executables_and_examples_output

before_build:
  - if not exist "C:\projects\clcache\install" mkdir C:\projects\clcache\install & pip3 install --target=C:\projects\clcache\install clcache
  - ps: $Clcacheserver = Start-Process clcache-server -PassThru
  - ps: fsutil behavior set disablelastaccess 0 # Enable Access time feature on Windows (for clcache)
  - clcache -M 2147483648 & clcache -s
  - if not exist "C:\projects\deps" call "C:\projects\SmartPeak2\ci\prepare_deps.bat"
  - if not exist "C:\projects\OpenMS" git clone --depth=1 --branch develop https://github.com/OpenMS/OpenMS.git C:\projects\OpenMS
  - if not exist "C:\projects\OpenMS-build" call "C:\projects\SmartPeak2\ci\build_openms.bat"
  - if not exist "C:\projects\SmartPeak2\build" call "C:\projects\SmartPeak2\ci\cmake_smartpeak.bat"

build_script:
  - cd C:\projects\SmartPeak2\build
  - #msbuild SmartPeak_host.sln /verbosity:normal /maxcpucount /p:TrackFileAccess=false /p:CLToolExe=clcache.exe /p:CLToolPath=C:\projects\clcache\install\bin
  - msbuild src\smartpeak\SmartPeak.sln /verbosity:normal /maxcpucount /p:TrackFileAccess=false /p:CLToolExe=clcache.exe /p:CLToolPath=C:\projects\clcache\install\bin
  - msbuild src\tests\class_tests\SmartPeak_class_tests.sln /verbosity:normal /maxcpucount /p:TrackFileAccess=false /p:CLToolExe=clcache.exe /p:CLToolPath=C:\projects\clcache\install\bin
  - msbuild src\examples\SmartPeak_class_examples_smartpeak.sln /verbosity:normal /maxcpucount /p:TrackFileAccess=false /p:CLToolExe=clcache.exe /p:CLToolPath=C:\projects\clcache\install\bin

after_build:
  - ps: fsutil behavior set disablelastaccess 1 # Disable Access time feature on Windows (better performance)
  - ps: Stop-Process -Id $Clcacheserver.Id
  - clcache -s & clcache -z

test_script:
  - cd C:\projects\SmartPeak2\build
  - ctest -C "Debug" -V -j2
#   - cd bin\Debug
#   - echo %time%
#   - C:\projects\SmartPeak2\build\bin\Debug\GCMS_SIM_Unknown_test > GCMS_SIM_Unknown_test.txt 2>&1
#   - echo %time%
#   - C:\projects\SmartPeak2\build\bin\Debug\HPLC_UV_Standards_test > HPLC_UV_Standards_test.txt 2>&1
#   - echo %time%
#   - C:\projects\SmartPeak2\build\bin\Debug\HPLC_UV_Unknown_test > HPLC_UV_Unknown_test.txt 2>&1
#   - echo %time%
#   - C:\projects\SmartPeak2\build\bin\Debug\LCMS_MRM_QCs_test > LCMS_MRM_QCs_test.txt 2>&1
#   - echo %time%
#   - C:\projects\SmartPeak2\build\bin\Debug\LCMS_MRM_Unknown_test > LCMS_MRM_Unknown_test.txt 2>&1
#   - echo %time%
