version: '1.0.{build}'
image: Visual Studio 2017
environment:
  APPVEYOR_RDP_PASSWORD: z1x2c3V4
  BOOSTROOT: C:\Libraries\boost_1_69_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_69_0\lib64-msvc-14.1
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_69_0
  Boost_DEBUG: TRUE
init:
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - mkdir C:\projects\deps
platform:
  - x64
configuration:
  - Debug
cache:
#  - C:\projects\deps
  - C:\projects\OpenMS-build
install:
  - git submodule update --init --recursive
  - pushd util\install-dep-windows\ && install-dependencies-win.bat & popd
  - 7z x C:\projects\deps\contrib_build.tar.gz -o"C:\projects\deps" -y
  - 7z x C:\projects\deps\contrib_build.tar -o"C:\projects\deps\contrib" -y
  - dir C:\projects\deps\contrib
  - dir C:\Qt\5.12.1
  - dir C:\Libraries\boost_1_69_0
before_build:
#  - git clone --branch chore/replace_boost_regex https://github.com/biosustain/OpenMS.git C:\projects\OpenMS-build
#  - ps: cd C:\projects\OpenMS-build
#  - cmake  -DCMAKE_PREFIX_PATH="C:\Qt\5.12.1\msvc2017_64\lib\cmake" -DBoost_DEBUG=TRUE -DCMAKE_GENERATOR_PLATFORM=x64 -DBoost_NO_SYSTEM_PATHS=ON -DBOOST_LIBRARYDIR="C:\Libraries\boost_1_69_0\lib64-msvc-14.1" -DBOOST_INCLUDEDIR="C:\Libraries\boost_1_69_0" -DBOOST_ROOT="C:\Libraries\boost_1_69_0\boost" -DOPENMS_CONTRIB_LIBS="C:/projects/deps/contrib" -DBOOST_USE_STATIC=ON -DHAS_XSERVER=OFF -DWITH_GUI=OFF -DENABLE_TUTORIALS=OFF -DENABLE_DOCS=OFF -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DCMAKE_BUILD_TYPE=Debug -DPYOPENMS=OFF -DOPENMS_COVERAGE=OFF C:\projects\OpenMS-build -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
#  - dir C:\projects\OpenMS-build\src\openms
#  - msbuild C:\projects\OpenMS-build\src\openswathalgo\OpenSWATHAlgo.sln
#  - msbuild C:\projects\OpenMS-build\src\openms\OpenMS.sln
#  - msbuild C:\projects\OpenMS-build\OpenMS_host.sln
  - cmake -DCMAKE_PREFIX_PATH="C:\projects\OpenMS-build;C:\Qt\5.12.1\msvc2017_64\lib\cmake" -G "Visual Studio 15 2017 Win64" -T host=x64 -DEIGEN3_INCLUDE_DIR="C:\projects\deps\contrib\include\eigen3" -DBOOST_INCLUDEDIR="C:\Libraries\boost_1_69_0" -DBOOST_LIBRARYDIR="C:\Libraries\boost_1_69_0\lib64-msvc-14.1" -DEIGEN_USE_GPU=OFF -DUSE_SUPERBUILD=OFF -DBOOST_USE_STATIC=OFF -DCMAKE_BUILD_TYPE=Debug C:\projects\smartpeak2
  - dir C:\projects\smartpeak2 
build:
  project: C:\projects\smartpeak2\SmartPeak_host.sln 
  #project: C:\projects\OpenMS-build\src\openms\OpenMS.sln
test_script:
  #- C:\projects\smartpeak2\bin\Debug\GCMS_SIM_Unknown_test
  - C:\projects\smartpeak2\bin\Debug\HPLC_UV_Standards_test
  - C:\projects\smartpeak2\bin\Debug\HPLC_UV_Unknown_test
  - C:\projects\smartpeak2\bin\Debug\LCMS_MRM_QCs_test
  - C:\projects\smartpeak2\bin\Debug\LCMS_MRM_Standards_test
  - C:\projects\smartpeak2\bin\Debug\LCMS_MRM_Unknown_test