version: '1.0.{build}'
image: Visual Studio 2017
init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - mkdir C:\projects\deps

  platform:
  - x64
configuration:
  - Debug
cache:
    - xsd-4.0.msi -> appveyor.yml
install:
    - git submodule update --init --recursive
    - pushd util\install-dep-windows\ && install-dependencies-win.bat & popd
    - 7z x C:\projects\deps\contrib_build.tar.gz -o"C:\projects\deps\contrib" -y
    - dir C:\projects\deps\contrib
    - git clone --branch chore/replace_boost_regex https://github.com/biosustain/OpenMS.git C:\projects\OpenMS-build
before_build:
    - cd C:\projects\OpenMS-build
    - git submodule update --init contrib
    - mkdir contrib_win64_build
    - cd contrib_win64_build
    - cmake -DBUILD_TYPE=ALL -DNUMBER_OF_JOBS=4 -G "Visual Studio 15 2017 Win64" "c:\projects\OpenMS-build\contrib"
    - ps: cd C:\projects\OpenMS-build
    - cmake -D OPENMS_CONTRIB_LIBS="C:\projects\OpenMS-build\contrib_win64_build" -DBOOST_USE_STATIC=OFF -DHAS_XSERVER=OFF -DWITH_GUI=OFF -DENABLE_TUTORIALS=OFF -DENABLE_DOCS=OFF -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DCMAKE_BUILD_TYPE=Debug -DPYOPENMS=OFF -DOPENMS_COVERAGE=OFF C:\projects\OpenMS-build -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
build:
  project: $(APPVEYOR_BUILD_FOLDER)/$(APPVEYOR_PROJECT_NAME).sln