version: '1.0.{build}'
image: Visual Studio 2017
force_https_clone: true
clone_depth: 1
environment:
  APPVEYOR_RDP_PASSWORD: z1x2c3V4
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  BOOST_TEST_DETECT_MEMORY_LEAK: 0
  CLCACHE_DIR: C:\projects\clcache

# scripts that are called at very beginning, before repo cloning
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - PATH=C:\Python37-x64;C:\Python37-x64\Scripts;C:\projects\clcache\install;C:\projects\OpenMS-build\bin\Debug;C:\Qt\5.12.2\msvc2017_64\bin;C:\projects\deps\SDL2-2.0.9\lib\x64;%PATH%
  - set PYTHONPATH=C:\projects\clcache\install
  - cmake --version
  - pip3 --version

platform: x64
configuration: Debug

cache:
  - C:\projects\deps
  - C:\projects\OpenMS
  - C:\projects\OpenMS-build
  - C:\projects\clcache

# artifacts can only be found in the repo dir (i.e. C:\projects\SmartPeak2) or subdirs
artifacts:
  - path: build\bin\Debug
    name: executables_and_examples_output

before_build:
  - if not exist "C:\projects\clcache\install" mkdir C:\projects\clcache\install & pip3 install --target=C:\projects\clcache\install clcache
  - if not exist "C:\projects\deps" call "C:\projects\SmartPeak2\ci\prepare_deps.bat"
  - if not exist "C:\projects\OpenMS" git clone --depth=1 --branch chore/replace_boost_regex https://github.com/biosustain/OpenMS.git C:\projects\OpenMS
  - if not exist "C:\projects\OpenMS-build" call "C:\projects\SmartPeak2\ci\build_openms.bat"
  - if not exist "C:\projects\SmartPeak2\build" call "C:\projects\SmartPeak2\ci\cmake_smartpeak.bat"

build_script:
  - cd C:\projects\SmartPeak2\build
  - msbuild SmartPeak_host.sln /verbosity:normal /maxcpucount /p:CLToolExe=clcache.exe /p:CLToolPath=C:\projects\clcache\install\bin

test_script:
  - cd C:\projects\SmartPeak2\build
  - ctest -C "Debug" -V
  - C:\projects\SmartPeak2\.circleci\run_examples.sh C:\projects\SmartPeak2\build\bin\Debug C:\cygwin64\bin\
