version: '1.0.{build}'
image: Visual Studio 2017
platform:
  - x64
configuration:
  - Release
  - Debug
install:
    - git submodule update --init --recursive
before_build:
    - cmake -DEIGEN_USE_GPU=OFF -DUSE_SUPERBUILD=OFF -DBOOST_USE_STATIC=OFF -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=$HOME/OpenMS-build/ -DCMAKE_BUILD_TYPE=Debug
build:
  project: $(APPVEYOR_BUILD_FOLDER)/$(APPVEYOR_PROJECT_NAME).sln