version: '1.0.{build}'
image: Visual Studio 2017
force_https_clone: true
clone_depth: 1
environment:
  APPVEYOR_RDP_PASSWORD: z1x2c3V4
  BOOSTROOT: C:\Libraries\boost_1_69_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_69_0\lib64-msvc-14.1
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_69_0
  Boost_DEBUG: TRUE
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - mkdir C:\projects\deps
  - PATH=%PATH%;C:\projects\OpenMS-build\bin\Debug;C:\Qt\5.12\msvc2017_64\bin;C:\Libraries\boost_1_69_0\lib64-msvc-14.1

platform:
  - x64
configuration:
  - Debug
cache:
#  - C:\projects\deps
  - C:\projects\OpenMS-build
install:
  - git submodule update --init --recursive
  - pushd util\install-dep-windows\ && install-dependencies-win.bat & popd
  - 7z x C:\projects\deps\contrib_build.tar.gz -o"C:\projects\deps" -y
  - 7z x C:\projects\deps\contrib_build.tar -o"C:\projects\deps\contrib" -y
  - dir C:\projects\deps\contrib
  - dir C:\Qt\5.12
  - dir C:\Libraries\boost_1_69_0
before_build:
  - ps: |
      if(![System.IO.File]::Exists("C:\projects\OpenMS-build")) {
        git clone --depth=1 --branch chore/replace_boost_regex https://github.com/biosustain/OpenMS.git C:\projects\OpenMS
        mkdir C:\projects\OpenMS-build
        cd C:\projects\OpenMS-build
        cmake -DCMAKE_PREFIX_PATH="C:\Qt\5.12\msvc2017_64\lib\cmake" -DBoost_DEBUG=TRUE -DCMAKE_GENERATOR_PLATFORM=x64 -DBoost_NO_SYSTEM_PATHS=ON -DBOOST_LIBRARYDIR="C:\Libraries\boost_1_69_0\lib64-msvc-14.1" -DBOOST_INCLUDEDIR="C:\Libraries\boost_1_69_0" -DBOOST_ROOT="C:\Libraries\boost_1_69_0\boost" -DOPENMS_CONTRIB_LIBS="C:/projects/deps/contrib" -DBOOST_USE_STATIC=ON -DHAS_XSERVER=OFF -DWITH_GUI=OFF -DENABLE_TUTORIALS=OFF -DENABLE_DOCS=OFF -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DCMAKE_BUILD_TYPE=Debug -DPYOPENMS=OFF -DOPENMS_COVERAGE=OFF C:\projects\OpenMS-build -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON C:\projects\OpenMS
        dir C:\projects\OpenMS-build\src\openms
        msbuild C:\projects\OpenMS-build\src\openswathalgo\OpenSWATHAlgo.sln -maxcpucount
        msbuild C:\projects\OpenMS-build\src\openms\OpenMS.sln -maxcpucount
      }
  - dir C:\projects\SmartPeak2
  - cd C:\projects
  - git clone -n https://github.com/SergiusTheBest/plog.git
  - cd plog
  - git checkout 5f69a631086bf038e2c0feee4319a485c34fa863
  - cd C:\projects
  - git clone -n https://github.com/ocornut/imgui.git
  - cd imgui
  - git checkout ebe79bbed00a13fd4455f04131b63d49c28ebd5d
  - cd C:\projects
  - curl -fsS -o SDL2-devel-2.0.9-VC.zip https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip
  - dir C:\projects\deps
  - 7z x SDL2-devel-2.0.9-VC.zip -o"C:\projects\deps" -y
  - dir C:\projects\deps
  - mkdir C:\projects\SmartPeak2-build
  - cd C:\projects\SmartPeak2-build
  - cmake -DCMAKE_PREFIX_PATH="C:\projects\OpenMS-build;C:\Qt\5.12\msvc2017_64\lib\cmake;C:\projects\deps\SDL2-2.0.9" -G "Visual Studio 15 2017 Win64" -T host=x64 -DEIGEN3_INCLUDE_DIR="C:\projects\deps\contrib\include\eigen3" -DBOOST_INCLUDEDIR="C:\Libraries\boost_1_69_0" -DBOOST_LIBRARYDIR="C:\Libraries\boost_1_69_0\lib64-msvc-14.1" -DPLOG_INCLUDE_DIR="C:/projects/plog/include" -DIMGUI_DIR="C:/projects/imgui" -DEIGEN_USE_GPU=OFF -DUSE_SUPERBUILD=OFF -DBOOST_USE_STATIC=OFF -DCMAKE_BUILD_TYPE=Debug C:\projects\SmartPeak2
  - dir C:\projects\SmartPeak2-build
build:
  parallel: true
  verbosity: detailed
  project: C:\projects\SmartPeak2\SmartPeak_host.sln
  #project: C:\projects\OpenMS-build\src\openms\OpenMS.sln

#test_script:
#  - dir C:\projects\smartpeak2\bin\Debug\
#  - ps: C:\projects\smartpeak2\bin\Debug\GCMS_SIM_Unknown_test.exe
#  - ps: C:\projects\smartpeak2\bin\Debug\HPLC_UV_Standards_test.exe
#  - ps: C:\projects\smartpeak2\bin\Debug\HPLC_UV_Unknown_test.exe
#  - ps: C:\projects\smartpeak2\bin\Debug\LCMS_MRM_QCs_test.exe
#  - ps: C:\projects\smartpeak2\bin\Debug\LCMS_MRM_Standards_test.exe
#  - ps: C:\projects\smartpeak2\bin\Debug\LCMS_MRM_Unknown_test.exe