version: '1.0.{build}'
image: Visual Studio 2017
platform:
  - x64
configuration:
  - Debug
cache:
    - xsd-4.0.msi -> appveyor.yml
install:
    - git submodule update --init --recursive
    - mkdir C:\projects\deps
    - pushd util\install-dep-windows\ && install-dependencies-win.bat & popd
    - dir C:\projects\deps\xsd\lib\vc-12.0
before_build:
    - echo %CD%
    - mkdir foo
    - echo %CD%
    - ps: cd foo
    - echo %CD%
    - git clone --branch chore/replace_boost_regex https://github.com/biosustain/OpenMS.git C:\projects\OpenMS-build
    - ps: cd C:\projects\OpenMS-build
    - cmake -DCMAKE_PREFIX_PATH="C:\projects\deps\xsd\lib\vc-12.0" -DCMAKE_INCLUDE_PATH="C:\projects\deps\xsd\include\xercesc" -DXercesC_INCLUDE_DIRS="C:\projects\deps\xsd\include\xercesc" -DBOOST_ROOT=C:\Libraries\boost_1_69_0 -DBOOST_USE_STATIC=OFF -DHAS_XSERVER=OFF -DWITH_GUI=OFF -DENABLE_TUTORIALS=OFF -DENABLE_DOCS=OFF -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DCMAKE_BUILD_TYPE=Debug -DPYOPENMS=OFF -DOPENMS_COVERAGE=OFF C:\projects\OpenMS-build
    # -DXercesC_LIBRARIES="C:\projects\deps\xsd\lib\vc-12.0"
    #- 
    #- ps: cd C:\projects\smartpeak2
    #- cmake -DEIGEN_USE_GPU=OFF -DUSE_SUPERBUILD=OFF -DBOOST_USE_STATIC=OFF -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=$HOME/OpenMS-build/ -DCMAKE_BUILD_TYPE=Debug
build:
  project: $(APPVEYOR_BUILD_FOLDER)/$(APPVEYOR_PROJECT_NAME).sln