

version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build_ubuntu:
    docker:
      - image: ubuntu:18.04

    working_directory: ~/SmartPeak2

    resource_class: large

    steps:
      - checkout
      - run: |
          apt-get update
      - run: >
          apt-get install -y git cmake qt5-default libboost-dev libeigen3-dev
          libxerces-c-dev coinor-libcbc-dev libsvm-dev libboost-iostreams-dev
          libboost-date-time-dev libboost-math-dev libwildmagic-dev libsqlite3-dev
          libglpk-dev seqan-dev libsdl2-dev libhdf5-dev libboost-filesystem-dev
      - run: |
          cd ~ &&
          git clone --branch develop --depth 1 https://github.com/OpenMS/OpenMS.git &&
          cd OpenMS && git submodule update --init THIRDPARTY &&
          cmake -DBOOST_USE_STATIC=OFF -DHAS_XSERVER=OFF -DWITH_GUI=OFF -DENABLE_TUTORIALS=OFF -DENABLE_DOCS=OFF -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DCMAKE_BUILD_TYPE=Debug -DPYOPENMS=OFF -DOPENMS_COVERAGE=OFF ~/OpenMS &&
          make -j4 OpenMS
      - run:
          command: |
            mkdir ~/SmartPeak2_superbuild
            cd ~/SmartPeak2_superbuild
            cmake -DUSE_SUPERBUILD=ON -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ~/SmartPeak2
            make -j4
      - run:
          command: |
            mkdir ~/SmartPeak2_build
            cd ~/SmartPeak2_build
            cmake -DEIGEN_USE_GPU=OFF -DUSE_SUPERBUILD=OFF -DBOOST_USE_STATIC=OFF -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=$HOME/OpenMS-build/ -DPLOG_INCLUDE_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/plog/include -DIMGUI_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/imgui -DImGui_INCLUDE_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/imgui -DIMPLOT_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/implot -DCMAKE_BUILD_TYPE=Debug ~/SmartPeak2
            make -j4
      - run:
          command: |
            cd ~/SmartPeak2_build || exit 1
            ls -l ~/SmartPeak2/src/tests/class_tests/smartpeak/data
            ctest -V
            ls -l ~/SmartPeak2/src/tests/class_tests/smartpeak/data
      - run:
          command: |
            ~/SmartPeak2/.circleci/run_examples.sh ~/SmartPeak2_build/bin

  build_windows:
    working_directory: ~/SmartPeak2
    executor: win/default
    steps:
      - checkout
      - run: systeminfo
      - run: |
          cd ~
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          $ProgressPreference = "SilentlyContinue"
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install cmake
          choco install doxygen.install
          $qt_url = 'https://github.com/martinrotter/qt5-minimalistic-builds/releases/download/5.12.9/qt-5.12.9-dynamic-msvc2019-x86_64.7z'
          $boost_url = 'https://github.com/ahmedskhalil/Boost-1.73-Prebuilts/releases/download/0.0.1/boost_1_73_0.7z'
          $qt_tmp = New-TemporaryFile | Rename-Item -NewName { $_ -replace 'qt_tmp$', '7z' } –PassThru
          Invoke-WebRequest $qt_url -OutFile $qt_tmp 
          7z x $qt_tmp -o'C:\lib\Qt'
          $Qt_DIR = 'C:\lib\Qt\qt-5.12.9-dynamic-msvc2019-x86_64'
          $qt_tmp | Remove-Item
          $boost_tmp = New-TemporaryFile | Rename-Item -NewName { $_ -replace 'boost_tmp$', '7z' } –PassThru
          Invoke-WebRequest $boost_url -OutFile $boost_tmp 
          7z x $boost_tmp -o'C:\lib\boost'
          $Boost_DIR = 'C:\lib\boost'
          ls C:\lib\boost\boost_1_73_0\
          $boost_tmp | Remove-Item
          cd ~
          git clone --branch develop --depth 1 https://github.com/OpenMS/OpenMS.git
          cd ~/OpenMS; git submodule update --init contrib; mkdir contrib_build; cd contrib_build
          cmake -DBUILD_TYPE=ALL ~/OpenMS/contrib
          cd ~/OpenMS;  mkdir openms_debug_build; cd openms_debug_build
          cmake -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_EXTENSIONS=OFF -DOPENMS_CONTRIB_LIBS=../contrib_build -D CMAKE_PREFIX_PATH="C:\lib\boost\boost_1_73_0;C:\lib\Qt\qt-5.12.9-dynamic-msvc2019-x86_64" -DBOOST_USE_STATIC=OFF -DHAS_XSERVER=OFF -DWITH_GUI=OFF -DENABLE_TUTORIALS=OFF -DENABLE_DOCS=OFF -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DCMAKE_BUILD_TYPE=Debug -DPYOPENMS=OFF -DOPENMS_COVERAGE=OFF ~/OpenMS
          make -j4 OpenMS





workflows:
  version: 2
  build-deploy:
    jobs:
      - build_ubuntu
      - build_windows
