

version: 2.1
jobs:
  build_ubuntu:
    docker:
      - image: ubuntu:18.04

    working_directory: ~/SmartPeak2

    resource_class: large

    steps:
      - checkout
      - run: |
          apt-get update
      - run: >
          apt-get install -y git cmake qt5-default libboost-dev libeigen3-dev
          libxerces-c-dev coinor-libcbc-dev libsvm-dev libboost-iostreams-dev
          libboost-date-time-dev libboost-math-dev libwildmagic-dev libsqlite3-dev
          libglpk-dev seqan-dev libsdl2-dev libhdf5-dev libboost-filesystem-dev
      - run: |
          cd ~ &&
          git clone --branch develop --depth 1 https://github.com/OpenMS/OpenMS.git &&
          cd OpenMS && git submodule update --init THIRDPARTY &&
          cmake -DBOOST_USE_STATIC=OFF -DHAS_XSERVER=OFF -DWITH_GUI=OFF -DENABLE_TUTORIALS=OFF -DENABLE_DOCS=OFF -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DCMAKE_BUILD_TYPE=Debug -DPYOPENMS=OFF -DOPENMS_COVERAGE=OFF ~/OpenMS &&
          make -j4 OpenMS
      - run:
          command: |
            mkdir ~/SmartPeak2_superbuild
            cd ~/SmartPeak2_superbuild
            cmake -DUSE_SUPERBUILD=ON -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ~/SmartPeak2
            make -j4
      - run:
          command: |
            mkdir ~/SmartPeak2_build
            cd ~/SmartPeak2_build
            cmake -DEIGEN_USE_GPU=OFF -DUSE_SUPERBUILD=OFF -DBOOST_USE_STATIC=OFF -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=$HOME/OpenMS-build/ -DPLOG_INCLUDE_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/plog/include -DIMGUI_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/imgui -DImGui_INCLUDE_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/imgui -DCMAKE_BUILD_TYPE=Debug ~/SmartPeak2
            make -j4
      - run:
          command: |
            cd ~/SmartPeak2_build || exit 1
            ls -l ~/SmartPeak2/src/tests/class_tests/smartpeak/data
            ctest -V
            ls -l ~/SmartPeak2/src/tests/class_tests/smartpeak/data
      - run:
          command: |
            ~/SmartPeak2/.circleci/run_examples.sh ~/SmartPeak2_build/bin

  build_macos:
    macos:
      xcode: "11.0.0"
    resource_class: medium
    steps:
      - checkout
      - run: brew install cmake qt5 sdl2 boost glpk eigen sqlite brewsci/bio/seqan@2 hdf5 libsvm xerces-c
      - run: brew install coin-or-tools/coinor/cbc coin-or-tools/coinor/cgl coin-or-tools/coinor/clp coin-or-tools/coinor/coin_data_netlib
      - run: brew install coin-or-tools/coinor/coin_data_sample coin-or-tools/coinor/coinutils coin-or-tools/coinor/osi
      - run: |
          cd ~ &&
          git clone --branch develop --depth 1 https://github.com/OpenMS/OpenMS.git &&
          cd OpenMS && git submodule update --init contrib && mkdir contrib-build && cd contrib-build && 
          cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DBUILD_TYPE=ALL ../contrib &&
          cd ~/OpenMS &&  mkdir openms-debug-build && cd openms-debug-build &&
          cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_PREFIX_PATH="$(brew --prefix);$(brew --prefix qt5);$(brew --prefix boost)" -DBOOST_USE_STATIC=OFF -DOPENMS_CONTRIB_LIBS=../contrib_build/ -DCOIN_INCLUDE_DIR=../contrib_build/include/ -DHAS_XSERVER=OFF -DWITH_GUI=OFF -DENABLE_TUTORIALS=OFF -DENABLE_DOCS=OFF -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DCMAKE_BUILD_TYPE=Debug -DPYOPENMS=OFF -DOPENMS_COVERAGE=OFF ..
          make -j4 OpenMS


workflows:
  version: 2.1
  build:
    jobs:
      - build_ubuntu
      - build_macos
