

version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build_ubuntu:
    docker:
      - image: ubuntu:18.04

    working_directory: ~/SmartPeak2

    resource_class: large

    steps:
      - checkout
      - run: |
          apt-get update
      - run: >
          apt-get install -y git cmake qt5-default libboost-dev libeigen3-dev
          libxerces-c-dev coinor-libcbc-dev libsvm-dev libboost-iostreams-dev
          libboost-date-time-dev libboost-math-dev libwildmagic-dev libsqlite3-dev
          libglpk-dev seqan-dev libsdl2-dev libhdf5-dev libboost-filesystem-dev
      - run: |
          cd ~ &&
          git clone --branch develop --depth 1 https://github.com/OpenMS/OpenMS.git &&
          cd OpenMS && git submodule update --init THIRDPARTY &&
          cmake -DBOOST_USE_STATIC=OFF -DHAS_XSERVER=OFF -DWITH_GUI=OFF -DENABLE_TUTORIALS=OFF -DENABLE_DOCS=OFF -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DCMAKE_BUILD_TYPE=Debug -DPYOPENMS=OFF -DOPENMS_COVERAGE=OFF ~/OpenMS &&
          make -j4 OpenMS
      - run:
          command: |
            mkdir ~/SmartPeak2_superbuild
            cd ~/SmartPeak2_superbuild
            cmake -DUSE_SUPERBUILD=ON -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ~/SmartPeak2
            make -j4
      - run:
          command: |
            mkdir ~/SmartPeak2_build
            cd ~/SmartPeak2_build
            cmake -DEIGEN_USE_GPU=OFF -DUSE_SUPERBUILD=OFF -DBOOST_USE_STATIC=OFF -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=$HOME/OpenMS-build/ -DPLOG_INCLUDE_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/plog/include -DIMGUI_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/imgui -DImGui_INCLUDE_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/imgui -DIMPLOT_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/implot -DCMAKE_BUILD_TYPE=Debug ~/SmartPeak2
            make -j4
      - run:
          command: |
            cd ~/SmartPeak2_build || exit 1
            ls -l ~/SmartPeak2/src/tests/class_tests/smartpeak/data
            ctest -V
            ls -l ~/SmartPeak2/src/tests/class_tests/smartpeak/data
      - run:
          command: |
            ~/SmartPeak2/.circleci/run_examples.sh ~/SmartPeak2_build/bin

  build_windows:
    working_directory: ~/SmartPeak2
    executor: win/default
    steps:
      - checkout
      - run: systeminfo
      - run: |
          cd ~
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          $ProgressPreference = "SilentlyContinue"
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"'
          choco install doxygen.install
          refreshenv
          $qt_url = 'https://github.com/martinrotter/qt5-minimalistic-builds/releases/download/5.12.9/qt-5.12.9-dynamic-msvc2019-x86_64.7z'
          $sdl2_url = 'https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip'
          $qt_tmp = New-TemporaryFile | Rename-Item -NewName { $_ -replace 'qt_tmp$', '7z' } –PassThru
          Invoke-WebRequest $qt_url -OutFile $qt_tmp 
          7z x $qt_tmp -o'C:\lib\Qt'
          $Qt_DIR = 'C:\lib\Qt\qt-5.12.9-dynamic-msvc2019-x86_64'
          $qt_tmp | Remove-Item
          $sdl2_tmp = New-TemporaryFile | Rename-Item -NewName { $_ -replace 'sdl2_tmp$', '7z' } –PassThru
          Invoke-WebRequest $sdl2_url -OutFile $sdl2_tmp 
          7z x $sdl2_tmp -o'C:\lib\sdl2'
          $Qt_DIR = 'C:\lib\sdl2\SDL2-2.0.12'
          $sdl2_tmp | Remove-Item
      - run: |
          cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars64.txt"
          Get-Content "$env:temp\vcvars64.txt" | Foreach-Object {
            if ($_ -match "^(.*?)=(.*)$") {
              Set-Content "env:\$($matches[1])" $matches[2]
            }
          }
          cd ~
          git clone --branch develop --depth 1 https://github.com/OpenMS/OpenMS.git
          cd ~/OpenMS; git submodule update --init contrib; mkdir contrib_build; cd contrib_build
          cmake -DBUILD_TYPE=ALL ~/OpenMS/contrib
          cd ~/OpenMS; mkdir openms_debug_build; cd openms_debug_build
          cmake -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_EXTENSIONS=OFF -DOPENMS_CONTRIB_LIBS=~/OpenMS/contrib_build -DCMAKE_PREFIX_PATH="C:\lib\Qt\qt-5.12.9-dynamic-msvc2019-x86_64" -DHAS_XSERVER=OFF -DWITH_GUI=OFF -DENABLE_TUTORIALS=OFF -DENABLE_DOCS=OFF -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DCMAKE_BUILD_TYPE=Debug -DPYOPENMS=OFF -DOPENMS_COVERAGE=OFF ~/OpenMS
          cmake --build . --target OpenMS
          # cd ~; 7z a OpenMS OpenMS/*
      # - restore_cache:
          # keys:
            # - oms1-{{ checksum "OpenMS.7z" }}
      - run: |
          cd ~/SmartPeak2; mkdir smartpeak2_debug_superbuild, smartpeak2_debug_build
          cd smartpeak2_debug_superbuild
          cmake -DUSE_SUPERBUILD=ON -DCMAKE_BUILD_TYPE=Debug ~/SmartPeak2; cmake --build .
          cd ~/SmartPeak2/smartpeak2_debug_build
          cmake -DEIGEN_USE_GPU=OFF -DUSE_SUPERBUILD=OFF -DBOOST_USE_STATIC=OFF -DCMAKE_PREFIX_PATH="~/OpenMS/openms_debug_build/;~/OpenMS/contrib_build/;C:\lib\Qt\qt-5.12.9-dynamic-msvc2019-x86_64;C:\lib\sdl2\SDL2-2.0.12" -DPLOG_INCLUDE_DIR=~/SmartPeak2/smartpeak2_debug_superbuild/Dependencies/Source/plog/include -DIMGUI_DIR=~/SmartPeak2/smartpeak2_debug_superbuild/Dependencies/Source/imgui -DIMPLOT_DIR=~/SmartPeak2/smartpeak2_debug_superbuild/Dependencies/Source/implot -DCMAKE_BUILD_TYPE=Debug ~/SmartPeak2
          cmake --build .
          





workflows:
  version: 2
  build-deploy:
    jobs:
      - build_ubuntu
      - build_windows
