

version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build_ubuntu:
    docker:
      - image: ubuntu:18.04

    working_directory: ~/SmartPeak2

    resource_class: large

    steps:
      - checkout
      - run: |
          apt-get update
      - run: >
          apt-get install -y git cmake qt5-default libboost-dev libeigen3-dev
          libxerces-c-dev coinor-libcbc-dev libsvm-dev libboost-iostreams-dev
          libboost-date-time-dev libboost-math-dev libwildmagic-dev libsqlite3-dev
          libglpk-dev seqan-dev libsdl2-dev libhdf5-dev libboost-filesystem-dev
      - run: |
          cd ~ &&
          git clone --branch develop --depth 1 https://github.com/OpenMS/OpenMS.git &&
          cd OpenMS && git submodule update --init THIRDPARTY &&
          cmake -DBOOST_USE_STATIC=OFF -DHAS_XSERVER=OFF -DWITH_GUI=OFF -DENABLE_TUTORIALS=OFF -DENABLE_DOCS=OFF -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DCMAKE_BUILD_TYPE=Debug -DPYOPENMS=OFF -DOPENMS_COVERAGE=OFF ~/OpenMS &&
          make -j4 OpenMS
      - run:
          command: |
            mkdir ~/SmartPeak2_superbuild
            cd ~/SmartPeak2_superbuild
            cmake -DUSE_SUPERBUILD=ON -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ~/SmartPeak2
            make -j4
      - run:
          command: |
            mkdir ~/SmartPeak2_build
            cd ~/SmartPeak2_build
            cmake -DEIGEN_USE_GPU=OFF -DUSE_SUPERBUILD=OFF -DBoost_NO_SYSTEM_PATHS=OFF -DBOOST_USE_STATIC=OFF -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=$HOME/OpenMS-build/ -DPLOG_INCLUDE_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/plog/include -DIMGUI_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/imgui -DImGui_INCLUDE_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/imgui -DIMPLOT_DIR=$HOME/SmartPeak2_superbuild/Dependencies/Source/implot -DCMAKE_BUILD_TYPE=Debug ~/SmartPeak2
            make -j4
      - run:
          command: |
            cd ~/SmartPeak2_build || exit 1
            ls -l ~/SmartPeak2/src/tests/class_tests/smartpeak/data
            ctest -V
            ls -l ~/SmartPeak2/src/tests/class_tests/smartpeak/data
      - run:
          command: |
            ~/SmartPeak2/.circleci/run_examples.sh ~/SmartPeak2_build/bin


  build_windows:
    working_directory: ~/SmartPeak2
    executor: win/default
    steps:
      - checkout
      - run: systeminfo
      - run: |
          cd ~
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          $ProgressPreference = "SilentlyContinue"
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"'
          choco install visualstudio2017community
          choco install visualstudio2017buildtools
          choco install visualstudio2017-workload-nativedesktop
          choco install boost-msvc-14.1
          choco install doxygen.install
          choco install nsis
          refreshenv
          $qt_url = 'https://github.com/martinrotter/qt5-minimalistic-builds/releases/download/5.12.9/qt-5.12.9-dynamic-msvc2019-x86_64.7z'
          $sdl2_url = 'https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip'
          $boost_url = 'https://github.com/ahmedskhalil/Boost-1.73-Prebuilts/releases/download/0.0.1/boost_1_73_0.7z'
          $qt_tmp = New-TemporaryFile | Rename-Item -NewName { $_ -replace 'qt_tmp$', '7z' } –PassThru
          Invoke-WebRequest $qt_url -OutFile $qt_tmp 
          7z x $qt_tmp -o'C:\lib\Qt'
          $Qt_DIR = 'C:\lib\Qt\qt-5.12.9-dynamic-msvc2019-x86_64'
          $qt_tmp | Remove-Item
          $sdl2_tmp = New-TemporaryFile | Rename-Item -NewName { $_ -replace 'sdl2_tmp$', 'zip' } –PassThru
          Invoke-WebRequest $sdl2_url -OutFile $sdl2_tmp 
          7z x $sdl2_tmp -o'C:\lib\sdl2'
          $SDL_DIR = 'C:\lib\sdl2\SDL2-2.0.12'
          $sdl2_tmp | Remove-Item
          $boost_tmp = New-TemporaryFile | Rename-Item -NewName { $_ -replace 'boost_tmp$', '7z' } –PassThru
          Invoke-WebRequest $boost_url -OutFile $boost_tmp 
          7z x $boost_tmp -o'C:\lib\boost'
          ls C:\lib\boost\boost_1_73_0
          ls C:\local\boost
          ls C:\local\boost\boost_1_67_0
          $BOOST_DIR = 'C:\lib\boost\boost_1_73_0'
          $boost_tmp | Remove-Item
      - run: |
          # cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars64.txt"
          cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars64.txt"
          Get-Content "$env:temp\vcvars64.txt" | Foreach-Object {
            if ($_ -match "^(.*?)=(.*)$") {
              Set-Content "env:\$($matches[1])" $matches[2]
            }
          }
          cd ~
          git clone --branch develop --depth 1 https://github.com/OpenMS/OpenMS.git
          cd ~/OpenMS; git submodule update --init contrib; mkdir contrib_build; cd contrib_build
          cmake -G "Visual Studio 15 2017 Win64" -DBUILD_TYPE=SEQAN ~/OpenMS/contrib
          cmake -G "Visual Studio 15 2017 Win64" -DBUILD_TYPE=LIBSVM ~/OpenMS/contrib
          cmake -G "Visual Studio 15 2017 Win64" -DBUILD_TYPE=XERCESC ~/OpenMS/contrib
          cmake -G "Visual Studio 15 2017 Win64" -DBUILD_TYPE=COINOR ~/OpenMS/contrib
          cmake -G "Visual Studio 15 2017 Win64" -DBUILD_TYPE=BZIP2 ~/OpenMS/contrib
          cmake -G "Visual Studio 15 2017 Win64" -DBUILD_TYPE=ZLIB ~/OpenMS/contrib
          cmake -G "Visual Studio 15 2017 Win64" -DBUILD_TYPE=GLPK ~/OpenMS/contrib
          cmake -G "Visual Studio 15 2017 Win64" -DBUILD_TYPE=EIGEN ~/OpenMS/contrib
          cmake -G "Visual Studio 15 2017 Win64" -DBUILD_TYPE=WILDMAGIC ~/OpenMS/contrib
          cmake -G "Visual Studio 15 2017 Win64" -DBUILD_TYPE=SQLITE ~/OpenMS/contrib
          cmake -G "Visual Studio 15 2017 Win64" -DBUILD_TYPE=KISSFFT ~/OpenMS/contrib
          cmake -G "Visual Studio 15 2017 Win64" -DBUILD_TYPE=HDF5 ~/OpenMS/contrib
          cd ~/OpenMS; mkdir openms_debug_build; cd openms_debug_build
          # cmake -G "Visual Studio 16 2019" -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_EXTENSIONS=OFF -DCXX_STANDARD_REQUIRED=ON -DBoost_NO_SYSTEM_PATHS=ON -DBOOST_USE_STATIC=ON -DBOOST_ROOT="C:/lib/boost/boost_1_73_0" -DBOOST_INCLUDEDIR="C:/lib/boost/boost_1_73_0" -DBOOST_LIBRARYDIR="C:/lib/boost/boost_1_73_0/lib64-msvc-14.2" -DOPENMS_CONTRIB_LIBS=~/OpenMS/contrib_build -DCMAKE_PREFIX_PATH="C:/lib/Qt/qt-5.12.9-dynamic-msvc2019-x86_64" -DHAS_XSERVER=OFF -DWITH_GUI=OFF -DENABLE_TUTORIALS=OFF -DENABLE_DOCS=OFF -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DCMAKE_BUILD_TYPE=Debug -DPYOPENMS=OFF -DOPENMS_COVERAGE=OFF ~/OpenMS
          cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_EXTENSIONS=OFF -DCXX_STANDARD_REQUIRED=ON -DBoost_NO_SYSTEM_PATHS=ON -DBOOST_USE_STATIC=ON -DBOOST_ROOT="C:/local/boost_1_67_0" -DBOOST_INCLUDE_DIR="C:/local/boost_1_67_0" -DBOOST_LIBRARYDIR="C:/local/boost_1_67_0/lib64-msvc-14.1" -DOPENMS_CONTRIB_LIBS=~/OpenMS/contrib_build -DCMAKE_PREFIX_PATH="C:/lib/Qt/qt-5.12.9-dynamic-msvc2019-x86_64" -DHAS_XSERVER=OFF -DWITH_GUI=OFF -DENABLE_TUTORIALS=OFF -DENABLE_DOCS=OFF -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DCMAKE_BUILD_TYPE=Debug -DPYOPENMS=OFF -DOPENMS_COVERAGE=OFF ~/OpenMS
          cmake --build . --target OpenMS
          # cd ~; 7z a OpenMS OpenMS/*
      # - restore_cache:
          # keys:
            # - oms1-{{ checksum "OpenMS.7z" }}
      - run: |
          # cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars64.txt"
          Get-Content "$env:temp\vcvars64.txt" | Foreach-Object {
            if ($_ -match "^(.*?)=(.*)$") {
              Set-Content "env:\$($matches[1])" $matches[2]
            }
          }
          cd ~/SmartPeak2
          mkdir smartpeak2_debug_superbuild, smartpeak2_debug_build
          cd ~/SmartPeak2/smartpeak2_debug_superbuild
          cmake -DUSE_SUPERBUILD=ON -DCMAKE_BUILD_TYPE=Debug ~/SmartPeak2
          cmake --build .
          cd ~/SmartPeak2/smartpeak2_debug_build
          cmake -G "Visual Studio 16 2019" -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_EXTENSIONS=OFF -DCXX_STANDARD_REQUIRED=ON -DEIGEN_USE_GPU=OFF -DUSE_SUPERBUILD=OFF -DBoost_NO_SYSTEM_PATHS=ON -DBOOST_USE_STATIC=ON -DBOOST_ROOT="C:/local/boost_1_67_0" -DBOOST_INCLUDE_DIR=C:/local/boost_1_67_0 -DBOOST_LIBRARYDIR=C:/local/boost_1_67_0/lib64-msvc-14.1 -DCMAKE_PREFIX_PATH="~/OpenMS/openms_debug_build/;C:/lib/Qt/qt-5.12.9-dynamic-msvc2019-x86_64;C:/lib/sdl2/SDL2-2.0.12" -DEIGEN3_INCLUDE_DIR=C:/Users/circleci/OpenMS/contrib_build/include/eigen3 -DPLOG_INCLUDE_DIR=~/SmartPeak2/smartpeak2_debug_superbuild/Dependencies/Source/plog/include -DIMGUI_DIR=~/SmartPeak2/smartpeak2_debug_superbuild/Dependencies/Source/imgui -DIMPLOT_DIR=~/SmartPeak2/smartpeak2_debug_superbuild/Dependencies/Source/implot -DCMAKE_BUILD_TYPE=Debug ~/SmartPeak2
          cmake --build .
          # cpack
          ctest -VV -F
          

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_ubuntu
      - build_windows
