
#ifndef SMARTPEAK_PACKAGE_VERSION_H
#define SMARTPEAK_PACKAGE_VERSION_H

#define SMARTPEAK_PACKAGE_VERSION "1.0.0"
#define SMARTPEAK_GIT_SHA1 "93b2372"
#define SMARTPEAK_GIT_BRANCH "develop"

#endif
