# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ALL_INSTALL_TYPES "Full;Developer")
set(CPACK_BINARY_7Z "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "ON")
set(CPACK_BINARY_NUGET "OFF")
set(CPACK_BINARY_WIX "OFF")
set(CPACK_BINARY_ZIP "OFF")
set(CPACK_BUILD_SOURCE_DIRS "C:/Users/dmccloskey/Documents/GitHub/SmartPeak;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build")
set(CPACK_CMAKE_GENERATOR "Visual Studio 16 2019")
set(CPACK_COMPONENTS_ALL "share;library;applications;doc")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_APPLICATIONS_DESCRIPTION "SmartPeak executables to run the GUI or scripts")
set(CPACK_COMPONENT_APPLICATIONS_DISPLAY_NAME "SmartPeak binaries")
set(CPACK_COMPONENT_APPLICATIONS_GROUP "Runtime")
set(CPACK_COMPONENT_APPLICATIONS_INSTALL_TYPES "Full")
set(CPACK_COMPONENT_DOC_DESCRIPTION "Class documentation with tutorials")
set(CPACK_COMPONENT_DOC_DISPLAY_NAME "Documentation")
set(CPACK_COMPONENT_DOC_GROUP "Runtime")
set(CPACK_COMPONENT_DOC_INSTALL_TYPES "Full")
set(CPACK_COMPONENT_LIBRARY_DESCRIPTION "SmartPeak libraries for building applications against")
set(CPACK_COMPONENT_LIBRARY_DISPLAY_NAME "Libraries")
set(CPACK_COMPONENT_LIBRARY_GROUP "Runtime")
set(CPACK_COMPONENT_LIBRARY_INSTALL_TYPES "Full")
set(CPACK_COMPONENT_SHARE_DESCRIPTION "SmartPeak shared files")
set(CPACK_COMPONENT_SHARE_DISPLAY_NAME "SmartPeak shared files")
set(CPACK_COMPONENT_SHARE_GROUP "Development")
set(CPACK_COMPONENT_SHARE_INSTALL_TYPES "Developer;Full")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-3.17/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "SmartPeak_host built using CMake")
set(CPACK_GENERATOR "7Z;ZIP")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INSTALLED_DIRECTORIES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/SmartPeak_host")
set(CPACK_MODULE_PATH "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/cmake/modules;C:/Users/dmccloskey/Documents/GitHub/SmartPeak/cmake/Windows")
set(CPACK_NSIS_DISPLAY_NAME "SmartPeak-1.0.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "SmartPeak-1.0.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/cmake/SmartPeakPackageDescriptionFile.cmake")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "SmartPeak - metabolomics, lipidomics, proteomics, and fluxomics data processing")
set(CPACK_PACKAGE_FILE_NAME "SmartPeak-1.0.0-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "SmartPeak-1.0.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "SmartPeak-1.0.0")
set(CPACK_PACKAGE_NAME "SmartPeak")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "SmartPeak.com")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/LICENSE")
set(CPACK_RESOURCE_FILE_README "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/cmake/SmartPeakPackageResourceReadme.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/cmake/SmartPeakPackageResourceWelcomeFile.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "C:/Users/dmccloskey/Documents/GitHub/SmartPeak;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "SmartPeak-1.0.0-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "win64-Source")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_TOPLEVEL_TAG "win64-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
