# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget SmartPeak)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target SmartPeak
add_library(SmartPeak STATIC IMPORTED)

set_target_properties(SmartPeak PROPERTIES
  INTERFACE_LINK_LIBRARIES "C:/lib/sdl2/SDL2-2.0.12/lib/x64/SDL2main.lib;C:/lib/sdl2/SDL2-2.0.12/lib/x64/SDL2.lib;\$<\$<NOT:\$<CONFIG:DEBUG>>:C:/lib/boost/boost_1_73_0/lib64-msvc-14.2/libboost_filesystem-vc142-mt-x64-1_73.lib>;\$<\$<CONFIG:DEBUG>:C:/lib/boost/boost_1_73_0/lib64-msvc-14.2/libboost_filesystem-vc142-mt-gd-x64-1_73.lib>;opengl32.lib"
)

# Import target "SmartPeak" for configuration "Debug"
set_property(TARGET SmartPeak APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SmartPeak PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/lib/Debug/SmartPeakd.lib"
  )

# Import target "SmartPeak" for configuration "Release"
set_property(TARGET SmartPeak APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SmartPeak PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/lib/Release/SmartPeak.lib"
  )

# Import target "SmartPeak" for configuration "MinSizeRel"
set_property(TARGET SmartPeak APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SmartPeak PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/lib/MinSizeRel/SmartPeak.lib"
  )

# Import target "SmartPeak" for configuration "RelWithDebInfo"
set_property(TARGET SmartPeak APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SmartPeak PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/dmccloskey/Documents/GitHub/SmartPeak/smartpeak_build/lib/RelWithDebInfo/SmartPeak.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
