// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: workflow.proto
#ifndef GRPC_workflow_2eproto__INCLUDED
#define GRPC_workflow_2eproto__INCLUDED

#include "workflow.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace SmartPeakServer {

class Workflow final {
 public:
  static constexpr char const* service_full_name() {
    return "SmartPeakServer.Workflow";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status runWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::SmartPeakServer::WorkflowResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SmartPeakServer::WorkflowResult>> AsyncrunWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SmartPeakServer::WorkflowResult>>(AsyncrunWorkflowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SmartPeakServer::WorkflowResult>> PrepareAsyncrunWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SmartPeakServer::WorkflowResult>>(PrepareAsyncrunWorkflowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::SmartPeakServer::LogStream>> getLogStream(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::SmartPeakServer::LogStream>>(getLogStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::SmartPeakServer::LogStream>> AsyncgetLogStream(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::SmartPeakServer::LogStream>>(AsyncgetLogStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::SmartPeakServer::LogStream>> PrepareAsyncgetLogStream(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::SmartPeakServer::LogStream>>(PrepareAsyncgetLogStreamRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void runWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowResult* response, std::function<void(::grpc::Status)>) = 0;
      virtual void runWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowResult* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void getLogStream(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs* request, ::grpc::ClientReadReactor< ::SmartPeakServer::LogStream>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SmartPeakServer::WorkflowResult>* AsyncrunWorkflowRaw(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SmartPeakServer::WorkflowResult>* PrepareAsyncrunWorkflowRaw(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::SmartPeakServer::LogStream>* getLogStreamRaw(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::SmartPeakServer::LogStream>* AsyncgetLogStreamRaw(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::SmartPeakServer::LogStream>* PrepareAsyncgetLogStreamRaw(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status runWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::SmartPeakServer::WorkflowResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SmartPeakServer::WorkflowResult>> AsyncrunWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SmartPeakServer::WorkflowResult>>(AsyncrunWorkflowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SmartPeakServer::WorkflowResult>> PrepareAsyncrunWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SmartPeakServer::WorkflowResult>>(PrepareAsyncrunWorkflowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::SmartPeakServer::LogStream>> getLogStream(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::SmartPeakServer::LogStream>>(getLogStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::SmartPeakServer::LogStream>> AsyncgetLogStream(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::SmartPeakServer::LogStream>>(AsyncgetLogStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::SmartPeakServer::LogStream>> PrepareAsyncgetLogStream(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::SmartPeakServer::LogStream>>(PrepareAsyncgetLogStreamRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void runWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowResult* response, std::function<void(::grpc::Status)>) override;
      void runWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowResult* response, ::grpc::ClientUnaryReactor* reactor) override;
      void getLogStream(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs* request, ::grpc::ClientReadReactor< ::SmartPeakServer::LogStream>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::SmartPeakServer::WorkflowResult>* AsyncrunWorkflowRaw(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SmartPeakServer::WorkflowResult>* PrepareAsyncrunWorkflowRaw(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::SmartPeakServer::LogStream>* getLogStreamRaw(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request) override;
    ::grpc::ClientAsyncReader< ::SmartPeakServer::LogStream>* AsyncgetLogStreamRaw(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::SmartPeakServer::LogStream>* PrepareAsyncgetLogStreamRaw(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_runWorkflow_;
    const ::grpc::internal::RpcMethod rpcmethod_getLogStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status runWorkflow(::grpc::ServerContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowResult* response);
    virtual ::grpc::Status getLogStream(::grpc::ServerContext* context, const ::SmartPeakServer::InquireLogs* request, ::grpc::ServerWriter< ::SmartPeakServer::LogStream>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_runWorkflow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_runWorkflow() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_runWorkflow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status runWorkflow(::grpc::ServerContext* /*context*/, const ::SmartPeakServer::WorkflowParameters* /*request*/, ::SmartPeakServer::WorkflowResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrunWorkflow(::grpc::ServerContext* context, ::SmartPeakServer::WorkflowParameters* request, ::grpc::ServerAsyncResponseWriter< ::SmartPeakServer::WorkflowResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_getLogStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getLogStream() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_getLogStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getLogStream(::grpc::ServerContext* /*context*/, const ::SmartPeakServer::InquireLogs* /*request*/, ::grpc::ServerWriter< ::SmartPeakServer::LogStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetLogStream(::grpc::ServerContext* context, ::SmartPeakServer::InquireLogs* request, ::grpc::ServerAsyncWriter< ::SmartPeakServer::LogStream>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_runWorkflow<WithAsyncMethod_getLogStream<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_runWorkflow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_runWorkflow() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowResult>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowResult* response) { return this->runWorkflow(context, request, response); }));}
    void SetMessageAllocatorFor_runWorkflow(
        ::grpc::MessageAllocator< ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowResult>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowResult>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_runWorkflow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status runWorkflow(::grpc::ServerContext* /*context*/, const ::SmartPeakServer::WorkflowParameters* /*request*/, ::SmartPeakServer::WorkflowResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* runWorkflow(
      ::grpc::CallbackServerContext* /*context*/, const ::SmartPeakServer::WorkflowParameters* /*request*/, ::SmartPeakServer::WorkflowResult* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_getLogStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_getLogStream() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::SmartPeakServer::InquireLogs, ::SmartPeakServer::LogStream>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::SmartPeakServer::InquireLogs* request) { return this->getLogStream(context, request); }));
    }
    ~WithCallbackMethod_getLogStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getLogStream(::grpc::ServerContext* /*context*/, const ::SmartPeakServer::InquireLogs* /*request*/, ::grpc::ServerWriter< ::SmartPeakServer::LogStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::SmartPeakServer::LogStream>* getLogStream(
      ::grpc::CallbackServerContext* /*context*/, const ::SmartPeakServer::InquireLogs* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_runWorkflow<WithCallbackMethod_getLogStream<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_runWorkflow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_runWorkflow() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_runWorkflow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status runWorkflow(::grpc::ServerContext* /*context*/, const ::SmartPeakServer::WorkflowParameters* /*request*/, ::SmartPeakServer::WorkflowResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_getLogStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getLogStream() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_getLogStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getLogStream(::grpc::ServerContext* /*context*/, const ::SmartPeakServer::InquireLogs* /*request*/, ::grpc::ServerWriter< ::SmartPeakServer::LogStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_runWorkflow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_runWorkflow() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_runWorkflow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status runWorkflow(::grpc::ServerContext* /*context*/, const ::SmartPeakServer::WorkflowParameters* /*request*/, ::SmartPeakServer::WorkflowResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrunWorkflow(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_getLogStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getLogStream() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_getLogStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getLogStream(::grpc::ServerContext* /*context*/, const ::SmartPeakServer::InquireLogs* /*request*/, ::grpc::ServerWriter< ::SmartPeakServer::LogStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetLogStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_runWorkflow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_runWorkflow() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->runWorkflow(context, request, response); }));
    }
    ~WithRawCallbackMethod_runWorkflow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status runWorkflow(::grpc::ServerContext* /*context*/, const ::SmartPeakServer::WorkflowParameters* /*request*/, ::SmartPeakServer::WorkflowResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* runWorkflow(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_getLogStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_getLogStream() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->getLogStream(context, request); }));
    }
    ~WithRawCallbackMethod_getLogStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getLogStream(::grpc::ServerContext* /*context*/, const ::SmartPeakServer::InquireLogs* /*request*/, ::grpc::ServerWriter< ::SmartPeakServer::LogStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* getLogStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_runWorkflow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_runWorkflow() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowResult>* streamer) {
                       return this->StreamedrunWorkflow(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_runWorkflow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status runWorkflow(::grpc::ServerContext* /*context*/, const ::SmartPeakServer::WorkflowParameters* /*request*/, ::SmartPeakServer::WorkflowResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedrunWorkflow(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::SmartPeakServer::WorkflowParameters,::SmartPeakServer::WorkflowResult>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_runWorkflow<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_getLogStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_getLogStream() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::SmartPeakServer::InquireLogs, ::SmartPeakServer::LogStream>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::SmartPeakServer::InquireLogs, ::SmartPeakServer::LogStream>* streamer) {
                       return this->StreamedgetLogStream(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_getLogStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getLogStream(::grpc::ServerContext* /*context*/, const ::SmartPeakServer::InquireLogs* /*request*/, ::grpc::ServerWriter< ::SmartPeakServer::LogStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedgetLogStream(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::SmartPeakServer::InquireLogs,::SmartPeakServer::LogStream>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_getLogStream<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_runWorkflow<WithSplitStreamingMethod_getLogStream<Service > > StreamedService;
};

}  // namespace SmartPeakServer


#endif  // GRPC_workflow_2eproto__INCLUDED
