// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: workflow.proto

#include "workflow.grpc.pb.h"
#include "workflow.grpc.pb.cc"
#include "workflow.pb.h"
#include "workflow.pb.cc"