// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workflow.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_workflow_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_workflow_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_workflow_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_workflow_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_workflow_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_workflow_2eproto_metadata_getter(int index);
namespace SmartPeakServer {
class InquireLogs;
struct InquireLogsDefaultTypeInternal;
extern InquireLogsDefaultTypeInternal _InquireLogs_default_instance_;
class LogStream;
struct LogStreamDefaultTypeInternal;
extern LogStreamDefaultTypeInternal _LogStream_default_instance_;
class WorkflowParameters;
struct WorkflowParametersDefaultTypeInternal;
extern WorkflowParametersDefaultTypeInternal _WorkflowParameters_default_instance_;
class WorkflowStatus;
struct WorkflowStatusDefaultTypeInternal;
extern WorkflowStatusDefaultTypeInternal _WorkflowStatus_default_instance_;
}  // namespace SmartPeakServer
PROTOBUF_NAMESPACE_OPEN
template<> ::SmartPeakServer::InquireLogs* Arena::CreateMaybeMessage<::SmartPeakServer::InquireLogs>(Arena*);
template<> ::SmartPeakServer::LogStream* Arena::CreateMaybeMessage<::SmartPeakServer::LogStream>(Arena*);
template<> ::SmartPeakServer::WorkflowParameters* Arena::CreateMaybeMessage<::SmartPeakServer::WorkflowParameters>(Arena*);
template<> ::SmartPeakServer::WorkflowStatus* Arena::CreateMaybeMessage<::SmartPeakServer::WorkflowStatus>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace SmartPeakServer {

enum WorkflowParameters_ExportReport : int {
  WorkflowParameters_ExportReport_ALL = 0,
  WorkflowParameters_ExportReport_FEATUREDB = 1,
  WorkflowParameters_ExportReport_PIVOTTABLE = 2,
  WorkflowParameters_ExportReport_WorkflowParameters_ExportReport_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  WorkflowParameters_ExportReport_WorkflowParameters_ExportReport_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool WorkflowParameters_ExportReport_IsValid(int value);
constexpr WorkflowParameters_ExportReport WorkflowParameters_ExportReport_ExportReport_MIN = WorkflowParameters_ExportReport_ALL;
constexpr WorkflowParameters_ExportReport WorkflowParameters_ExportReport_ExportReport_MAX = WorkflowParameters_ExportReport_PIVOTTABLE;
constexpr int WorkflowParameters_ExportReport_ExportReport_ARRAYSIZE = WorkflowParameters_ExportReport_ExportReport_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WorkflowParameters_ExportReport_descriptor();
template<typename T>
inline const std::string& WorkflowParameters_ExportReport_Name(T enum_t_value) {
  static_assert(::std::is_same<T, WorkflowParameters_ExportReport>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function WorkflowParameters_ExportReport_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    WorkflowParameters_ExportReport_descriptor(), enum_t_value);
}
inline bool WorkflowParameters_ExportReport_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, WorkflowParameters_ExportReport* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<WorkflowParameters_ExportReport>(
    WorkflowParameters_ExportReport_descriptor(), name, value);
}
// ===================================================================

class WorkflowParameters PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SmartPeakServer.WorkflowParameters) */ {
 public:
  inline WorkflowParameters() : WorkflowParameters(nullptr) {}
  virtual ~WorkflowParameters();
  explicit constexpr WorkflowParameters(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WorkflowParameters(const WorkflowParameters& from);
  WorkflowParameters(WorkflowParameters&& from) noexcept
    : WorkflowParameters() {
    *this = ::std::move(from);
  }

  inline WorkflowParameters& operator=(const WorkflowParameters& from) {
    CopyFrom(from);
    return *this;
  }
  inline WorkflowParameters& operator=(WorkflowParameters&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WorkflowParameters& default_instance() {
    return *internal_default_instance();
  }
  static inline const WorkflowParameters* internal_default_instance() {
    return reinterpret_cast<const WorkflowParameters*>(
               &_WorkflowParameters_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(WorkflowParameters& a, WorkflowParameters& b) {
    a.Swap(&b);
  }
  inline void Swap(WorkflowParameters* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WorkflowParameters* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WorkflowParameters* New() const final {
    return CreateMaybeMessage<WorkflowParameters>(nullptr);
  }

  WorkflowParameters* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WorkflowParameters>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WorkflowParameters& from);
  void MergeFrom(const WorkflowParameters& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WorkflowParameters* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SmartPeakServer.WorkflowParameters";
  }
  protected:
  explicit WorkflowParameters(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_workflow_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  typedef WorkflowParameters_ExportReport ExportReport;
  static constexpr ExportReport ALL =
    WorkflowParameters_ExportReport_ALL;
  static constexpr ExportReport FEATUREDB =
    WorkflowParameters_ExportReport_FEATUREDB;
  static constexpr ExportReport PIVOTTABLE =
    WorkflowParameters_ExportReport_PIVOTTABLE;
  static inline bool ExportReport_IsValid(int value) {
    return WorkflowParameters_ExportReport_IsValid(value);
  }
  static constexpr ExportReport ExportReport_MIN =
    WorkflowParameters_ExportReport_ExportReport_MIN;
  static constexpr ExportReport ExportReport_MAX =
    WorkflowParameters_ExportReport_ExportReport_MAX;
  static constexpr int ExportReport_ARRAYSIZE =
    WorkflowParameters_ExportReport_ExportReport_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ExportReport_descriptor() {
    return WorkflowParameters_ExportReport_descriptor();
  }
  template<typename T>
  static inline const std::string& ExportReport_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ExportReport>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ExportReport_Name.");
    return WorkflowParameters_ExportReport_Name(enum_t_value);
  }
  static inline bool ExportReport_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      ExportReport* value) {
    return WorkflowParameters_ExportReport_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSequenceFileFieldNumber = 1,
    kReportMetadataFieldNumber = 3,
    kReportSampleTypesFieldNumber = 4,
    kIntegrityFieldNumber = 5,
    kExportFieldNumber = 2,
  };
  // string sequence_file = 1;
  void clear_sequence_file();
  const std::string& sequence_file() const;
  void set_sequence_file(const std::string& value);
  void set_sequence_file(std::string&& value);
  void set_sequence_file(const char* value);
  void set_sequence_file(const char* value, size_t size);
  std::string* mutable_sequence_file();
  std::string* release_sequence_file();
  void set_allocated_sequence_file(std::string* sequence_file);
  private:
  const std::string& _internal_sequence_file() const;
  void _internal_set_sequence_file(const std::string& value);
  std::string* _internal_mutable_sequence_file();
  public:

  // string report_metadata = 3;
  void clear_report_metadata();
  const std::string& report_metadata() const;
  void set_report_metadata(const std::string& value);
  void set_report_metadata(std::string&& value);
  void set_report_metadata(const char* value);
  void set_report_metadata(const char* value, size_t size);
  std::string* mutable_report_metadata();
  std::string* release_report_metadata();
  void set_allocated_report_metadata(std::string* report_metadata);
  private:
  const std::string& _internal_report_metadata() const;
  void _internal_set_report_metadata(const std::string& value);
  std::string* _internal_mutable_report_metadata();
  public:

  // string report_sample_types = 4;
  void clear_report_sample_types();
  const std::string& report_sample_types() const;
  void set_report_sample_types(const std::string& value);
  void set_report_sample_types(std::string&& value);
  void set_report_sample_types(const char* value);
  void set_report_sample_types(const char* value, size_t size);
  std::string* mutable_report_sample_types();
  std::string* release_report_sample_types();
  void set_allocated_report_sample_types(std::string* report_sample_types);
  private:
  const std::string& _internal_report_sample_types() const;
  void _internal_set_report_sample_types(const std::string& value);
  std::string* _internal_mutable_report_sample_types();
  public:

  // string integrity = 5;
  void clear_integrity();
  const std::string& integrity() const;
  void set_integrity(const std::string& value);
  void set_integrity(std::string&& value);
  void set_integrity(const char* value);
  void set_integrity(const char* value, size_t size);
  std::string* mutable_integrity();
  std::string* release_integrity();
  void set_allocated_integrity(std::string* integrity);
  private:
  const std::string& _internal_integrity() const;
  void _internal_set_integrity(const std::string& value);
  std::string* _internal_mutable_integrity();
  public:

  // .SmartPeakServer.WorkflowParameters.ExportReport export = 2;
  void clear_export_();
  ::SmartPeakServer::WorkflowParameters_ExportReport export_() const;
  void set_export_(::SmartPeakServer::WorkflowParameters_ExportReport value);
  private:
  ::SmartPeakServer::WorkflowParameters_ExportReport _internal_export_() const;
  void _internal_set_export_(::SmartPeakServer::WorkflowParameters_ExportReport value);
  public:

  // @@protoc_insertion_point(class_scope:SmartPeakServer.WorkflowParameters)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sequence_file_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr report_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr report_sample_types_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr integrity_;
  int export__;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_workflow_2eproto;
};
// -------------------------------------------------------------------

class WorkflowStatus PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SmartPeakServer.WorkflowStatus) */ {
 public:
  inline WorkflowStatus() : WorkflowStatus(nullptr) {}
  virtual ~WorkflowStatus();
  explicit constexpr WorkflowStatus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WorkflowStatus(const WorkflowStatus& from);
  WorkflowStatus(WorkflowStatus&& from) noexcept
    : WorkflowStatus() {
    *this = ::std::move(from);
  }

  inline WorkflowStatus& operator=(const WorkflowStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline WorkflowStatus& operator=(WorkflowStatus&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WorkflowStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const WorkflowStatus* internal_default_instance() {
    return reinterpret_cast<const WorkflowStatus*>(
               &_WorkflowStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(WorkflowStatus& a, WorkflowStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(WorkflowStatus* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WorkflowStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WorkflowStatus* New() const final {
    return CreateMaybeMessage<WorkflowStatus>(nullptr);
  }

  WorkflowStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WorkflowStatus>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WorkflowStatus& from);
  void MergeFrom(const WorkflowStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WorkflowStatus* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SmartPeakServer.WorkflowStatus";
  }
  protected:
  explicit WorkflowStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_workflow_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusCodeFieldNumber = 2,
    kSessionIdFieldNumber = 3,
    kPathToResultsFieldNumber = 4,
    kProgressInPercentFieldNumber = 1,
  };
  // string status_code = 2;
  void clear_status_code();
  const std::string& status_code() const;
  void set_status_code(const std::string& value);
  void set_status_code(std::string&& value);
  void set_status_code(const char* value);
  void set_status_code(const char* value, size_t size);
  std::string* mutable_status_code();
  std::string* release_status_code();
  void set_allocated_status_code(std::string* status_code);
  private:
  const std::string& _internal_status_code() const;
  void _internal_set_status_code(const std::string& value);
  std::string* _internal_mutable_status_code();
  public:

  // string session_id = 3;
  void clear_session_id();
  const std::string& session_id() const;
  void set_session_id(const std::string& value);
  void set_session_id(std::string&& value);
  void set_session_id(const char* value);
  void set_session_id(const char* value, size_t size);
  std::string* mutable_session_id();
  std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

  // string path_to_results = 4;
  void clear_path_to_results();
  const std::string& path_to_results() const;
  void set_path_to_results(const std::string& value);
  void set_path_to_results(std::string&& value);
  void set_path_to_results(const char* value);
  void set_path_to_results(const char* value, size_t size);
  std::string* mutable_path_to_results();
  std::string* release_path_to_results();
  void set_allocated_path_to_results(std::string* path_to_results);
  private:
  const std::string& _internal_path_to_results() const;
  void _internal_set_path_to_results(const std::string& value);
  std::string* _internal_mutable_path_to_results();
  public:

  // int32 progress_in_percent = 1;
  void clear_progress_in_percent();
  ::PROTOBUF_NAMESPACE_ID::int32 progress_in_percent() const;
  void set_progress_in_percent(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_progress_in_percent() const;
  void _internal_set_progress_in_percent(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:SmartPeakServer.WorkflowStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_code_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_to_results_;
  ::PROTOBUF_NAMESPACE_ID::int32 progress_in_percent_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_workflow_2eproto;
};
// -------------------------------------------------------------------

class InquireLogs PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SmartPeakServer.InquireLogs) */ {
 public:
  inline InquireLogs() : InquireLogs(nullptr) {}
  virtual ~InquireLogs();
  explicit constexpr InquireLogs(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InquireLogs(const InquireLogs& from);
  InquireLogs(InquireLogs&& from) noexcept
    : InquireLogs() {
    *this = ::std::move(from);
  }

  inline InquireLogs& operator=(const InquireLogs& from) {
    CopyFrom(from);
    return *this;
  }
  inline InquireLogs& operator=(InquireLogs&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const InquireLogs& default_instance() {
    return *internal_default_instance();
  }
  static inline const InquireLogs* internal_default_instance() {
    return reinterpret_cast<const InquireLogs*>(
               &_InquireLogs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(InquireLogs& a, InquireLogs& b) {
    a.Swap(&b);
  }
  inline void Swap(InquireLogs* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InquireLogs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline InquireLogs* New() const final {
    return CreateMaybeMessage<InquireLogs>(nullptr);
  }

  InquireLogs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<InquireLogs>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const InquireLogs& from);
  void MergeFrom(const InquireLogs& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InquireLogs* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SmartPeakServer.InquireLogs";
  }
  protected:
  explicit InquireLogs(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_workflow_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNrLinesFieldNumber = 1,
  };
  // int32 nr_lines = 1;
  void clear_nr_lines();
  ::PROTOBUF_NAMESPACE_ID::int32 nr_lines() const;
  void set_nr_lines(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_nr_lines() const;
  void _internal_set_nr_lines(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:SmartPeakServer.InquireLogs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 nr_lines_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_workflow_2eproto;
};
// -------------------------------------------------------------------

class LogStream PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SmartPeakServer.LogStream) */ {
 public:
  inline LogStream() : LogStream(nullptr) {}
  virtual ~LogStream();
  explicit constexpr LogStream(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogStream(const LogStream& from);
  LogStream(LogStream&& from) noexcept
    : LogStream() {
    *this = ::std::move(from);
  }

  inline LogStream& operator=(const LogStream& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogStream& operator=(LogStream&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LogStream& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogStream* internal_default_instance() {
    return reinterpret_cast<const LogStream*>(
               &_LogStream_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(LogStream& a, LogStream& b) {
    a.Swap(&b);
  }
  inline void Swap(LogStream* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogStream* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LogStream* New() const final {
    return CreateMaybeMessage<LogStream>(nullptr);
  }

  LogStream* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LogStream>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LogStream& from);
  void MergeFrom(const LogStream& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogStream* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SmartPeakServer.LogStream";
  }
  protected:
  explicit LogStream(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_workflow_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLogLineFieldNumber = 1,
  };
  // string log_line = 1;
  void clear_log_line();
  const std::string& log_line() const;
  void set_log_line(const std::string& value);
  void set_log_line(std::string&& value);
  void set_log_line(const char* value);
  void set_log_line(const char* value, size_t size);
  std::string* mutable_log_line();
  std::string* release_log_line();
  void set_allocated_log_line(std::string* log_line);
  private:
  const std::string& _internal_log_line() const;
  void _internal_set_log_line(const std::string& value);
  std::string* _internal_mutable_log_line();
  public:

  // @@protoc_insertion_point(class_scope:SmartPeakServer.LogStream)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr log_line_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_workflow_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WorkflowParameters

// string sequence_file = 1;
inline void WorkflowParameters::clear_sequence_file() {
  sequence_file_.ClearToEmpty();
}
inline const std::string& WorkflowParameters::sequence_file() const {
  // @@protoc_insertion_point(field_get:SmartPeakServer.WorkflowParameters.sequence_file)
  return _internal_sequence_file();
}
inline void WorkflowParameters::set_sequence_file(const std::string& value) {
  _internal_set_sequence_file(value);
  // @@protoc_insertion_point(field_set:SmartPeakServer.WorkflowParameters.sequence_file)
}
inline std::string* WorkflowParameters::mutable_sequence_file() {
  // @@protoc_insertion_point(field_mutable:SmartPeakServer.WorkflowParameters.sequence_file)
  return _internal_mutable_sequence_file();
}
inline const std::string& WorkflowParameters::_internal_sequence_file() const {
  return sequence_file_.Get();
}
inline void WorkflowParameters::_internal_set_sequence_file(const std::string& value) {
  
  sequence_file_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void WorkflowParameters::set_sequence_file(std::string&& value) {
  
  sequence_file_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:SmartPeakServer.WorkflowParameters.sequence_file)
}
inline void WorkflowParameters::set_sequence_file(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sequence_file_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:SmartPeakServer.WorkflowParameters.sequence_file)
}
inline void WorkflowParameters::set_sequence_file(const char* value,
    size_t size) {
  
  sequence_file_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:SmartPeakServer.WorkflowParameters.sequence_file)
}
inline std::string* WorkflowParameters::_internal_mutable_sequence_file() {
  
  return sequence_file_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* WorkflowParameters::release_sequence_file() {
  // @@protoc_insertion_point(field_release:SmartPeakServer.WorkflowParameters.sequence_file)
  return sequence_file_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void WorkflowParameters::set_allocated_sequence_file(std::string* sequence_file) {
  if (sequence_file != nullptr) {
    
  } else {
    
  }
  sequence_file_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sequence_file,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:SmartPeakServer.WorkflowParameters.sequence_file)
}

// .SmartPeakServer.WorkflowParameters.ExportReport export = 2;
inline void WorkflowParameters::clear_export_() {
  export__ = 0;
}
inline ::SmartPeakServer::WorkflowParameters_ExportReport WorkflowParameters::_internal_export_() const {
  return static_cast< ::SmartPeakServer::WorkflowParameters_ExportReport >(export__);
}
inline ::SmartPeakServer::WorkflowParameters_ExportReport WorkflowParameters::export_() const {
  // @@protoc_insertion_point(field_get:SmartPeakServer.WorkflowParameters.export)
  return _internal_export_();
}
inline void WorkflowParameters::_internal_set_export_(::SmartPeakServer::WorkflowParameters_ExportReport value) {
  
  export__ = value;
}
inline void WorkflowParameters::set_export_(::SmartPeakServer::WorkflowParameters_ExportReport value) {
  _internal_set_export_(value);
  // @@protoc_insertion_point(field_set:SmartPeakServer.WorkflowParameters.export)
}

// string report_metadata = 3;
inline void WorkflowParameters::clear_report_metadata() {
  report_metadata_.ClearToEmpty();
}
inline const std::string& WorkflowParameters::report_metadata() const {
  // @@protoc_insertion_point(field_get:SmartPeakServer.WorkflowParameters.report_metadata)
  return _internal_report_metadata();
}
inline void WorkflowParameters::set_report_metadata(const std::string& value) {
  _internal_set_report_metadata(value);
  // @@protoc_insertion_point(field_set:SmartPeakServer.WorkflowParameters.report_metadata)
}
inline std::string* WorkflowParameters::mutable_report_metadata() {
  // @@protoc_insertion_point(field_mutable:SmartPeakServer.WorkflowParameters.report_metadata)
  return _internal_mutable_report_metadata();
}
inline const std::string& WorkflowParameters::_internal_report_metadata() const {
  return report_metadata_.Get();
}
inline void WorkflowParameters::_internal_set_report_metadata(const std::string& value) {
  
  report_metadata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void WorkflowParameters::set_report_metadata(std::string&& value) {
  
  report_metadata_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:SmartPeakServer.WorkflowParameters.report_metadata)
}
inline void WorkflowParameters::set_report_metadata(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  report_metadata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:SmartPeakServer.WorkflowParameters.report_metadata)
}
inline void WorkflowParameters::set_report_metadata(const char* value,
    size_t size) {
  
  report_metadata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:SmartPeakServer.WorkflowParameters.report_metadata)
}
inline std::string* WorkflowParameters::_internal_mutable_report_metadata() {
  
  return report_metadata_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* WorkflowParameters::release_report_metadata() {
  // @@protoc_insertion_point(field_release:SmartPeakServer.WorkflowParameters.report_metadata)
  return report_metadata_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void WorkflowParameters::set_allocated_report_metadata(std::string* report_metadata) {
  if (report_metadata != nullptr) {
    
  } else {
    
  }
  report_metadata_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), report_metadata,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:SmartPeakServer.WorkflowParameters.report_metadata)
}

// string report_sample_types = 4;
inline void WorkflowParameters::clear_report_sample_types() {
  report_sample_types_.ClearToEmpty();
}
inline const std::string& WorkflowParameters::report_sample_types() const {
  // @@protoc_insertion_point(field_get:SmartPeakServer.WorkflowParameters.report_sample_types)
  return _internal_report_sample_types();
}
inline void WorkflowParameters::set_report_sample_types(const std::string& value) {
  _internal_set_report_sample_types(value);
  // @@protoc_insertion_point(field_set:SmartPeakServer.WorkflowParameters.report_sample_types)
}
inline std::string* WorkflowParameters::mutable_report_sample_types() {
  // @@protoc_insertion_point(field_mutable:SmartPeakServer.WorkflowParameters.report_sample_types)
  return _internal_mutable_report_sample_types();
}
inline const std::string& WorkflowParameters::_internal_report_sample_types() const {
  return report_sample_types_.Get();
}
inline void WorkflowParameters::_internal_set_report_sample_types(const std::string& value) {
  
  report_sample_types_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void WorkflowParameters::set_report_sample_types(std::string&& value) {
  
  report_sample_types_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:SmartPeakServer.WorkflowParameters.report_sample_types)
}
inline void WorkflowParameters::set_report_sample_types(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  report_sample_types_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:SmartPeakServer.WorkflowParameters.report_sample_types)
}
inline void WorkflowParameters::set_report_sample_types(const char* value,
    size_t size) {
  
  report_sample_types_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:SmartPeakServer.WorkflowParameters.report_sample_types)
}
inline std::string* WorkflowParameters::_internal_mutable_report_sample_types() {
  
  return report_sample_types_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* WorkflowParameters::release_report_sample_types() {
  // @@protoc_insertion_point(field_release:SmartPeakServer.WorkflowParameters.report_sample_types)
  return report_sample_types_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void WorkflowParameters::set_allocated_report_sample_types(std::string* report_sample_types) {
  if (report_sample_types != nullptr) {
    
  } else {
    
  }
  report_sample_types_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), report_sample_types,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:SmartPeakServer.WorkflowParameters.report_sample_types)
}

// string integrity = 5;
inline void WorkflowParameters::clear_integrity() {
  integrity_.ClearToEmpty();
}
inline const std::string& WorkflowParameters::integrity() const {
  // @@protoc_insertion_point(field_get:SmartPeakServer.WorkflowParameters.integrity)
  return _internal_integrity();
}
inline void WorkflowParameters::set_integrity(const std::string& value) {
  _internal_set_integrity(value);
  // @@protoc_insertion_point(field_set:SmartPeakServer.WorkflowParameters.integrity)
}
inline std::string* WorkflowParameters::mutable_integrity() {
  // @@protoc_insertion_point(field_mutable:SmartPeakServer.WorkflowParameters.integrity)
  return _internal_mutable_integrity();
}
inline const std::string& WorkflowParameters::_internal_integrity() const {
  return integrity_.Get();
}
inline void WorkflowParameters::_internal_set_integrity(const std::string& value) {
  
  integrity_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void WorkflowParameters::set_integrity(std::string&& value) {
  
  integrity_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:SmartPeakServer.WorkflowParameters.integrity)
}
inline void WorkflowParameters::set_integrity(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  integrity_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:SmartPeakServer.WorkflowParameters.integrity)
}
inline void WorkflowParameters::set_integrity(const char* value,
    size_t size) {
  
  integrity_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:SmartPeakServer.WorkflowParameters.integrity)
}
inline std::string* WorkflowParameters::_internal_mutable_integrity() {
  
  return integrity_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* WorkflowParameters::release_integrity() {
  // @@protoc_insertion_point(field_release:SmartPeakServer.WorkflowParameters.integrity)
  return integrity_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void WorkflowParameters::set_allocated_integrity(std::string* integrity) {
  if (integrity != nullptr) {
    
  } else {
    
  }
  integrity_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), integrity,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:SmartPeakServer.WorkflowParameters.integrity)
}

// -------------------------------------------------------------------

// WorkflowStatus

// int32 progress_in_percent = 1;
inline void WorkflowStatus::clear_progress_in_percent() {
  progress_in_percent_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WorkflowStatus::_internal_progress_in_percent() const {
  return progress_in_percent_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WorkflowStatus::progress_in_percent() const {
  // @@protoc_insertion_point(field_get:SmartPeakServer.WorkflowStatus.progress_in_percent)
  return _internal_progress_in_percent();
}
inline void WorkflowStatus::_internal_set_progress_in_percent(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  progress_in_percent_ = value;
}
inline void WorkflowStatus::set_progress_in_percent(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_progress_in_percent(value);
  // @@protoc_insertion_point(field_set:SmartPeakServer.WorkflowStatus.progress_in_percent)
}

// string status_code = 2;
inline void WorkflowStatus::clear_status_code() {
  status_code_.ClearToEmpty();
}
inline const std::string& WorkflowStatus::status_code() const {
  // @@protoc_insertion_point(field_get:SmartPeakServer.WorkflowStatus.status_code)
  return _internal_status_code();
}
inline void WorkflowStatus::set_status_code(const std::string& value) {
  _internal_set_status_code(value);
  // @@protoc_insertion_point(field_set:SmartPeakServer.WorkflowStatus.status_code)
}
inline std::string* WorkflowStatus::mutable_status_code() {
  // @@protoc_insertion_point(field_mutable:SmartPeakServer.WorkflowStatus.status_code)
  return _internal_mutable_status_code();
}
inline const std::string& WorkflowStatus::_internal_status_code() const {
  return status_code_.Get();
}
inline void WorkflowStatus::_internal_set_status_code(const std::string& value) {
  
  status_code_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void WorkflowStatus::set_status_code(std::string&& value) {
  
  status_code_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:SmartPeakServer.WorkflowStatus.status_code)
}
inline void WorkflowStatus::set_status_code(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  status_code_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:SmartPeakServer.WorkflowStatus.status_code)
}
inline void WorkflowStatus::set_status_code(const char* value,
    size_t size) {
  
  status_code_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:SmartPeakServer.WorkflowStatus.status_code)
}
inline std::string* WorkflowStatus::_internal_mutable_status_code() {
  
  return status_code_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* WorkflowStatus::release_status_code() {
  // @@protoc_insertion_point(field_release:SmartPeakServer.WorkflowStatus.status_code)
  return status_code_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void WorkflowStatus::set_allocated_status_code(std::string* status_code) {
  if (status_code != nullptr) {
    
  } else {
    
  }
  status_code_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), status_code,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:SmartPeakServer.WorkflowStatus.status_code)
}

// string session_id = 3;
inline void WorkflowStatus::clear_session_id() {
  session_id_.ClearToEmpty();
}
inline const std::string& WorkflowStatus::session_id() const {
  // @@protoc_insertion_point(field_get:SmartPeakServer.WorkflowStatus.session_id)
  return _internal_session_id();
}
inline void WorkflowStatus::set_session_id(const std::string& value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:SmartPeakServer.WorkflowStatus.session_id)
}
inline std::string* WorkflowStatus::mutable_session_id() {
  // @@protoc_insertion_point(field_mutable:SmartPeakServer.WorkflowStatus.session_id)
  return _internal_mutable_session_id();
}
inline const std::string& WorkflowStatus::_internal_session_id() const {
  return session_id_.Get();
}
inline void WorkflowStatus::_internal_set_session_id(const std::string& value) {
  
  session_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void WorkflowStatus::set_session_id(std::string&& value) {
  
  session_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:SmartPeakServer.WorkflowStatus.session_id)
}
inline void WorkflowStatus::set_session_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  session_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:SmartPeakServer.WorkflowStatus.session_id)
}
inline void WorkflowStatus::set_session_id(const char* value,
    size_t size) {
  
  session_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:SmartPeakServer.WorkflowStatus.session_id)
}
inline std::string* WorkflowStatus::_internal_mutable_session_id() {
  
  return session_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* WorkflowStatus::release_session_id() {
  // @@protoc_insertion_point(field_release:SmartPeakServer.WorkflowStatus.session_id)
  return session_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void WorkflowStatus::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    
  } else {
    
  }
  session_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), session_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:SmartPeakServer.WorkflowStatus.session_id)
}

// string path_to_results = 4;
inline void WorkflowStatus::clear_path_to_results() {
  path_to_results_.ClearToEmpty();
}
inline const std::string& WorkflowStatus::path_to_results() const {
  // @@protoc_insertion_point(field_get:SmartPeakServer.WorkflowStatus.path_to_results)
  return _internal_path_to_results();
}
inline void WorkflowStatus::set_path_to_results(const std::string& value) {
  _internal_set_path_to_results(value);
  // @@protoc_insertion_point(field_set:SmartPeakServer.WorkflowStatus.path_to_results)
}
inline std::string* WorkflowStatus::mutable_path_to_results() {
  // @@protoc_insertion_point(field_mutable:SmartPeakServer.WorkflowStatus.path_to_results)
  return _internal_mutable_path_to_results();
}
inline const std::string& WorkflowStatus::_internal_path_to_results() const {
  return path_to_results_.Get();
}
inline void WorkflowStatus::_internal_set_path_to_results(const std::string& value) {
  
  path_to_results_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void WorkflowStatus::set_path_to_results(std::string&& value) {
  
  path_to_results_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:SmartPeakServer.WorkflowStatus.path_to_results)
}
inline void WorkflowStatus::set_path_to_results(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  path_to_results_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:SmartPeakServer.WorkflowStatus.path_to_results)
}
inline void WorkflowStatus::set_path_to_results(const char* value,
    size_t size) {
  
  path_to_results_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:SmartPeakServer.WorkflowStatus.path_to_results)
}
inline std::string* WorkflowStatus::_internal_mutable_path_to_results() {
  
  return path_to_results_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* WorkflowStatus::release_path_to_results() {
  // @@protoc_insertion_point(field_release:SmartPeakServer.WorkflowStatus.path_to_results)
  return path_to_results_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void WorkflowStatus::set_allocated_path_to_results(std::string* path_to_results) {
  if (path_to_results != nullptr) {
    
  } else {
    
  }
  path_to_results_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path_to_results,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:SmartPeakServer.WorkflowStatus.path_to_results)
}

// -------------------------------------------------------------------

// InquireLogs

// int32 nr_lines = 1;
inline void InquireLogs::clear_nr_lines() {
  nr_lines_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 InquireLogs::_internal_nr_lines() const {
  return nr_lines_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 InquireLogs::nr_lines() const {
  // @@protoc_insertion_point(field_get:SmartPeakServer.InquireLogs.nr_lines)
  return _internal_nr_lines();
}
inline void InquireLogs::_internal_set_nr_lines(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  nr_lines_ = value;
}
inline void InquireLogs::set_nr_lines(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_nr_lines(value);
  // @@protoc_insertion_point(field_set:SmartPeakServer.InquireLogs.nr_lines)
}

// -------------------------------------------------------------------

// LogStream

// string log_line = 1;
inline void LogStream::clear_log_line() {
  log_line_.ClearToEmpty();
}
inline const std::string& LogStream::log_line() const {
  // @@protoc_insertion_point(field_get:SmartPeakServer.LogStream.log_line)
  return _internal_log_line();
}
inline void LogStream::set_log_line(const std::string& value) {
  _internal_set_log_line(value);
  // @@protoc_insertion_point(field_set:SmartPeakServer.LogStream.log_line)
}
inline std::string* LogStream::mutable_log_line() {
  // @@protoc_insertion_point(field_mutable:SmartPeakServer.LogStream.log_line)
  return _internal_mutable_log_line();
}
inline const std::string& LogStream::_internal_log_line() const {
  return log_line_.Get();
}
inline void LogStream::_internal_set_log_line(const std::string& value) {
  
  log_line_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void LogStream::set_log_line(std::string&& value) {
  
  log_line_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:SmartPeakServer.LogStream.log_line)
}
inline void LogStream::set_log_line(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  log_line_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:SmartPeakServer.LogStream.log_line)
}
inline void LogStream::set_log_line(const char* value,
    size_t size) {
  
  log_line_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:SmartPeakServer.LogStream.log_line)
}
inline std::string* LogStream::_internal_mutable_log_line() {
  
  return log_line_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* LogStream::release_log_line() {
  // @@protoc_insertion_point(field_release:SmartPeakServer.LogStream.log_line)
  return log_line_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogStream::set_allocated_log_line(std::string* log_line) {
  if (log_line != nullptr) {
    
  } else {
    
  }
  log_line_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), log_line,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:SmartPeakServer.LogStream.log_line)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace SmartPeakServer

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::SmartPeakServer::WorkflowParameters_ExportReport> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SmartPeakServer::WorkflowParameters_ExportReport>() {
  return ::SmartPeakServer::WorkflowParameters_ExportReport_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_workflow_2eproto
