// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: workflow.proto

#include "workflow.pb.h"
#include "workflow.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace SmartPeakServer {

static const char* Workflow_method_names[] = {
  "/SmartPeakServer.Workflow/runWorkflow",
  "/SmartPeakServer.Workflow/getLogStream",
  "/SmartPeakServer.Workflow/getProgressInfo",
  "/SmartPeakServer.Workflow/getWorkflowEvent",
  "/SmartPeakServer.Workflow/stopRunningWorkflow",
};

std::unique_ptr< Workflow::Stub> Workflow::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Workflow::Stub> stub(new Workflow::Stub(channel, options));
  return stub;
}

Workflow::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_runWorkflow_(Workflow_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getLogStream_(Workflow_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_getProgressInfo_(Workflow_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getWorkflowEvent_(Workflow_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_stopRunningWorkflow_(Workflow_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Workflow::Stub::runWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::SmartPeakServer::WorkflowResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_runWorkflow_, context, request, response);
}

void Workflow::Stub::async::runWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_runWorkflow_, context, request, response, std::move(f));
}

void Workflow::Stub::async::runWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_runWorkflow_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SmartPeakServer::WorkflowResult>* Workflow::Stub::PrepareAsyncrunWorkflowRaw(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SmartPeakServer::WorkflowResult, ::SmartPeakServer::WorkflowParameters, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_runWorkflow_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SmartPeakServer::WorkflowResult>* Workflow::Stub::AsyncrunWorkflowRaw(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncrunWorkflowRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::SmartPeakServer::LogStream>* Workflow::Stub::getLogStreamRaw(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request) {
  return ::grpc::internal::ClientReaderFactory< ::SmartPeakServer::LogStream>::Create(channel_.get(), rpcmethod_getLogStream_, context, request);
}

void Workflow::Stub::async::getLogStream(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs* request, ::grpc::ClientReadReactor< ::SmartPeakServer::LogStream>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::SmartPeakServer::LogStream>::Create(stub_->channel_.get(), stub_->rpcmethod_getLogStream_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::SmartPeakServer::LogStream>* Workflow::Stub::AsyncgetLogStreamRaw(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::SmartPeakServer::LogStream>::Create(channel_.get(), cq, rpcmethod_getLogStream_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::SmartPeakServer::LogStream>* Workflow::Stub::PrepareAsyncgetLogStreamRaw(::grpc::ClientContext* context, const ::SmartPeakServer::InquireLogs& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::SmartPeakServer::LogStream>::Create(channel_.get(), cq, rpcmethod_getLogStream_, context, request, false, nullptr);
}

::grpc::Status Workflow::Stub::getProgressInfo(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::SmartPeakServer::ProgressInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::ProgressInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getProgressInfo_, context, request, response);
}

void Workflow::Stub::async::getProgressInfo(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::ProgressInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::ProgressInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getProgressInfo_, context, request, response, std::move(f));
}

void Workflow::Stub::async::getProgressInfo(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::ProgressInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getProgressInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SmartPeakServer::ProgressInfo>* Workflow::Stub::PrepareAsyncgetProgressInfoRaw(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SmartPeakServer::ProgressInfo, ::SmartPeakServer::WorkflowParameters, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getProgressInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SmartPeakServer::ProgressInfo>* Workflow::Stub::AsyncgetProgressInfoRaw(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetProgressInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Workflow::Stub::getWorkflowEvent(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::SmartPeakServer::WorkflowEvent* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowEvent, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getWorkflowEvent_, context, request, response);
}

void Workflow::Stub::async::getWorkflowEvent(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowEvent* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowEvent, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getWorkflowEvent_, context, request, response, std::move(f));
}

void Workflow::Stub::async::getWorkflowEvent(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowEvent* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getWorkflowEvent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SmartPeakServer::WorkflowEvent>* Workflow::Stub::PrepareAsyncgetWorkflowEventRaw(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SmartPeakServer::WorkflowEvent, ::SmartPeakServer::WorkflowParameters, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getWorkflowEvent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SmartPeakServer::WorkflowEvent>* Workflow::Stub::AsyncgetWorkflowEventRaw(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetWorkflowEventRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Workflow::Stub::stopRunningWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::Interrupter& request, ::SmartPeakServer::Interrupter* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SmartPeakServer::Interrupter, ::SmartPeakServer::Interrupter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_stopRunningWorkflow_, context, request, response);
}

void Workflow::Stub::async::stopRunningWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::Interrupter* request, ::SmartPeakServer::Interrupter* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SmartPeakServer::Interrupter, ::SmartPeakServer::Interrupter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_stopRunningWorkflow_, context, request, response, std::move(f));
}

void Workflow::Stub::async::stopRunningWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::Interrupter* request, ::SmartPeakServer::Interrupter* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_stopRunningWorkflow_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SmartPeakServer::Interrupter>* Workflow::Stub::PrepareAsyncstopRunningWorkflowRaw(::grpc::ClientContext* context, const ::SmartPeakServer::Interrupter& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SmartPeakServer::Interrupter, ::SmartPeakServer::Interrupter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_stopRunningWorkflow_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SmartPeakServer::Interrupter>* Workflow::Stub::AsyncstopRunningWorkflowRaw(::grpc::ClientContext* context, const ::SmartPeakServer::Interrupter& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncstopRunningWorkflowRaw(context, request, cq);
  result->StartCall();
  return result;
}

Workflow::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Workflow_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Workflow::Service, ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Workflow::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SmartPeakServer::WorkflowParameters* req,
             ::SmartPeakServer::WorkflowResult* resp) {
               return service->runWorkflow(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Workflow_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Workflow::Service, ::SmartPeakServer::InquireLogs, ::SmartPeakServer::LogStream>(
          [](Workflow::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SmartPeakServer::InquireLogs* req,
             ::grpc::ServerWriter<::SmartPeakServer::LogStream>* writer) {
               return service->getLogStream(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Workflow_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Workflow::Service, ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::ProgressInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Workflow::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SmartPeakServer::WorkflowParameters* req,
             ::SmartPeakServer::ProgressInfo* resp) {
               return service->getProgressInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Workflow_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Workflow::Service, ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowEvent, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Workflow::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SmartPeakServer::WorkflowParameters* req,
             ::SmartPeakServer::WorkflowEvent* resp) {
               return service->getWorkflowEvent(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Workflow_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Workflow::Service, ::SmartPeakServer::Interrupter, ::SmartPeakServer::Interrupter, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Workflow::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SmartPeakServer::Interrupter* req,
             ::SmartPeakServer::Interrupter* resp) {
               return service->stopRunningWorkflow(ctx, req, resp);
             }, this)));
}

Workflow::Service::~Service() {
}

::grpc::Status Workflow::Service::runWorkflow(::grpc::ServerContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Workflow::Service::getLogStream(::grpc::ServerContext* context, const ::SmartPeakServer::InquireLogs* request, ::grpc::ServerWriter< ::SmartPeakServer::LogStream>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Workflow::Service::getProgressInfo(::grpc::ServerContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::ProgressInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Workflow::Service::getWorkflowEvent(::grpc::ServerContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowEvent* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Workflow::Service::stopRunningWorkflow(::grpc::ServerContext* context, const ::SmartPeakServer::Interrupter* request, ::SmartPeakServer::Interrupter* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace SmartPeakServer

