// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: workflow.proto

#include "workflow.pb.h"
#include "workflow.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace SmartPeakServer {

static const char* Workflow_method_names[] = {
  "/SmartPeakServer.Workflow/runWorkflow",
};

std::unique_ptr< Workflow::Stub> Workflow::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Workflow::Stub> stub(new Workflow::Stub(channel, options));
  return stub;
}

Workflow::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_runWorkflow_(Workflow_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Workflow::Stub::runWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::SmartPeakServer::WorkflowStatus* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_runWorkflow_, context, request, response);
}

void Workflow::Stub::async::runWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_runWorkflow_, context, request, response, std::move(f));
}

void Workflow::Stub::async::runWorkflow(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowStatus* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_runWorkflow_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SmartPeakServer::WorkflowStatus>* Workflow::Stub::PrepareAsyncrunWorkflowRaw(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SmartPeakServer::WorkflowStatus, ::SmartPeakServer::WorkflowParameters, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_runWorkflow_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SmartPeakServer::WorkflowStatus>* Workflow::Stub::AsyncrunWorkflowRaw(::grpc::ClientContext* context, const ::SmartPeakServer::WorkflowParameters& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncrunWorkflowRaw(context, request, cq);
  result->StartCall();
  return result;
}

Workflow::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Workflow_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Workflow::Service, ::SmartPeakServer::WorkflowParameters, ::SmartPeakServer::WorkflowStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Workflow::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SmartPeakServer::WorkflowParameters* req,
             ::SmartPeakServer::WorkflowStatus* resp) {
               return service->runWorkflow(ctx, req, resp);
             }, this)));
}

Workflow::Service::~Service() {
}

::grpc::Status Workflow::Service::runWorkflow(::grpc::ServerContext* context, const ::SmartPeakServer::WorkflowParameters* request, ::SmartPeakServer::WorkflowStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace SmartPeakServer

